### ISSUE TITLE
Previous Xs becoming ✓s even if failed

### ISSUE THREAD

**Issue by jamesdeluk** [iSoron/uhabits#857] opened 2021-03-19 18:28 UTC
## Description

A picture says a thousand words, so let's say 2000.

This habit is 3 days out of 7 (left-most is most recent, today):

![Screenshot_20210319-181806](https://user-images.githubusercontent.com/27723508/111825732-87d2ab00-8933-11eb-9173-3358a7b4aa36.jpg)

As you can see, I failed.

However, if I do it today:

![Screenshot_20210319-082534](https://user-images.githubusercontent.com/27723508/111826396-5d352200-8934-11eb-8d79-88c232880ddd.jpg)

All the previous ones - which were failed - become ticks.

This seems wrong and suggests I'm amazing and never lapsed. Yet for the 7 days yesterday and prior, I was failing.

Admittedly, then it would be how to differentiate between currently on a successful run, and previously failed. If they stayed as Xs I wouldn't know if I was on-track this week. Perhaps change the Xs to a different shade of the chosen colour if they're successful or not? I know there is always the far-left circle, but that never seems to work properly for me (maybe I misunderstand it, but I've been doing something almost daily for months and still only got 1/4 circle).

## System information
 - Phone: OnePlus 6
 - Phone Operating System: Android latest
 - App version: Latest

**Comment by lukaszlew** [comment] 2021-03-21 02:34
I agree, value of each tick should be a function of the past.

**Comment by hiqua** [comment] 2021-03-25 08:58
It seems that, now, a day is ticked if `it belongs to an interval of 7 days in which 3 days are ticked`.

I think you're advocating to consider only the interval finishing with the day. I think that'd be more intuitive, it's just annoying to change now since it'll break streaks from users.

I'm curious about your circle not reaching 100%, could you share a screenshot? Maybe rename the habit / description to remove the private stuff. The formula is documented somewhere and it's not linear, but I think you should still be at a higher score than 25%.

**Comment by iSoron** [comment] 2021-03-25 11:21
The value used to be a function of the past in the first versions of the app, but we had many issues. See #124.

**Comment by jamesdeluk** [comment] 2021-03-28 12:10
@iSoron Hmm, I see. The great thing about this app is the simplicity. Do you have any plans to implement a rolling-week vs calendar-week function, as discussed in #124?

@hiqua Screenshots:
![Screenshot_20210328-125516 (Custom)](https://user-images.githubusercontent.com/27723508/112751558-17eab180-9012-11eb-97d2-e324b6316458.jpg)![Screenshot_20210328-125527 (Custom)](https://user-images.githubusercontent.com/27723508/112751560-18834800-9012-11eb-96f7-a6f91761a364.jpg)![Screenshot_20210328-125534 (Custom)](https://user-images.githubusercontent.com/27723508/112751561-191bde80-9012-11eb-824f-f44e8f46d7c2.jpg)

The data is the same, only the repeats is different. Note how 1/14 days gives a score of 33%, whereas 10/14 days gives 90%. In other words, if you over-achieve, you score drops. I suppose this works for negative habits, but not (like most of mine) a _minimum_ of X times in Y days.

**Comment by hiqua** [comment] 2021-03-28 21:42
Regarding the score, I don't know exactly how the additional ticks (that were not needed to complete the habit) are taken into account, but it makes sense that they do not make your score 100%.

The idea is a bit documented there: https://github.com/iSoron/uhabits/discussions/689 in "How is the score calculated?". I think it's also fine, given that you mostly want to evaluate how your score is evolving. You can also have a look at the formula there: https://github.com/iSoron/uhabits/blob/dev/uhabits-core/src/jvmMain/java/org/isoron/uhabits/core/models/Score.kt.

**Comment by iSoron** [comment] 2021-04-01 12:00
@jamesdeluk The score drop shown in your charts is expected. Less frequent habits take longer to reach 100% score, as described in the FAQ.

I am closing this issue, since all the behavior shown here is expected (to the developers of the app), and therefore not a bug.

**Closed by iSoron** 2021-04-01 12:00 UTC
