### ISSUE TITLE
[Feature request] Make it possible to write short notes attached to days

### ISSUE THREAD

**Issue by heretoenhance** [iSoron/uhabits#570] opened 2020-04-11 10:51 UTC
I think it would be very useful to have the possibility to write short notes to habit's days so that I can track not only if I did something one day but also how, or if I broke a streak I can write what happened. The user would then be able to read the notes clicking on the dots on the graph and/or on the History calendar squares.

Thank you for this amazing app!

**Comment by borjafv** [comment] 2020-04-11 11:25
I've been using the app for a long time and this is the only thing that I feel is missing. I use it to track stomach issues among other things and it would be awesome if I could write down what I ate the day that I felt sick.

Thanks for the effort put into the app, it's awesome.

**Comment by iSoron** [comment] 2020-04-11 16:23
Duplicate of #194

**Closed by iSoron** 2020-04-11 16:23 UTC
