### ISSUE TITLE
Add delete and archive buttons to menu in statistics screen

### ISSUE THREAD

**Issue by mr-flibble** [iSoron/uhabits#285] opened 2017-05-02 17:53 UTC
When I have open same habit in detail view, in context menu (three dots) only available option is "Export".
I think it would be great to add the option to delete habit (without fear of misclick on main screen)
Thanks

**Comment by iSoron** [comment] 2017-06-01 00:46
I agree that we could have this option there. We could also have archive or unarchive.

**Comment by pradeepmurugesan** [comment] 2017-07-17 08:31
@iSoron I installed the app yesterday and found this feature missing. Is it ok if I implement the same and send a PR ?

**Comment by iSoron** [comment] 2017-07-17 21:55
@pradeepmurugesan Sure, pull requests are very welcome!

**Comment by derebaba** [comment] 2017-10-24 15:20
@iSoron I am currently looking into this. This is my first android project so this might be noob question. Should I write classes which implement Task (e.g ArchiveHabitTask, DeleteHabitTask)? or add a CommandRunner object to ShowHabitMenuBehavior class and use ArchiveHabitsCommand and DeleteHabitsCommand?

**Comment by iSoron** [comment] 2017-10-27 02:45
@derebaba Thank you for working on this. You don't need to create any additional Tasks. You just need make `ShowHabitMenuBehavior` call `commandRunner.execute(new DeleteHabitsCommand(...))`. I expect the code to be very similar to what we currently have in `ListHabitsSelectionMenuBehavior`. You can have a look at that class and adapt the code, as necessary.

**Comment by derebaba** [comment] 2017-10-28 15:32
@iSoron Thank you for your answer. I can now successfully delete the habit. The problem is the app stays in statistics screen and it does not go to the list of habits after deleting (I can use the back button to go to list of habits to see that it is deleted). On the other hand, if I call `activity.finish()` in `showHabitScreen` after showing a confirmation dialog for deleting, it does not wait for an answer from the confirmation dialog (so it returns to list of habits without deleting). How can I make it wait for an answer?

**Comment by recheej** [comment] 2018-05-08 02:04
@iSoron Seems like this is now merged? Should this issue be closed now?

**Closed** 2018-08-12 02:00 UTC
Labels: small-enhancement, small-task

**Comment by Geeyun-JY3** [comment] 2021-01-25 23:44
So, there is still no archive buttion in statistics screen. Is it possible to add it?
