### ISSUE TITLE
Allow "All checked start"

### ISSUE THREAD

**Issue by slovanos** [iSoron/uhabits#614] opened 2020-07-30 07:56 UTC
First of all, thank you very much for the great and minimalist app!

I know, from the FAQs, that your suggestion for tracking bad habits is  "_rephrase your habit in a positive way_". Fine with me, but here my little suggestion: 

Could please add and option to set all days to be checked from the start?

The background of this is that if I set the goal, for example "No Smoking" or "No alcohol" the -let's say- "default" situation is that I do not drink alcohol every days, so it's a lot easier to just go to the app an "uncheck"  the day I did drink alcohol or felled into a bad habit, rather than of actively check everyday I didn't do it.

Does this suggestion makes sense to you? I'd really appreciate it

Best regards and congrats again on the great app!

**Comment by iSoron** [comment] 2020-08-13 11:35
Thank you for the suggestion. This is a duplicate of #125.

**Closed by iSoron** 2020-08-13 11:35 UTC
