### ISSUE TITLE
Hide completed not working

### ISSUE THREAD

**Issue by Lavin-tom** [iSoron/uhabits#1510] opened 2022-09-18 09:55 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
"Hide completed" option not working on non measurable habit

## Steps to reproduce
1. Go to ... Home page of Habit 
2. Click on .... Mark any of habit as complete
3. See error... Marked habits not hidden

## System information
 - Phone: [Samsung Galaxy M31s]
 - Phone Operating System: [Android 11]
 - App version: [2.1.0]

**Comment by hiqua** [comment] 2022-09-18 13:28
It works for me, could you share a screenshot of what you mean?

If you close the app and open it again does it work?

**Comment by iSoron** [comment] 2022-10-22 19:39
Closing as we do not have enough information to reproduce the issue.

**Closed by iSoron** 2022-10-22 19:39 UTC
Labels: bug, needs-info
