### ISSUE TITLE
Remove implicit negative response

### ISSUE THREAD

**Issue by Myridium** [iSoron/uhabits#602] opened 2020-07-02 06:50 UTC
I have used this app for almost a year now. 

A huge problem is that on days without a checkmark, there's no way to distinguish between whether I failed to record the habit that day, or whether I didn't perform the necessary action and made a conscious decision to leave it unchecked. For this reason, looking at the calendar history of habits provides little useful information to me. I have no idea whether I failed to record on any given day or if I failed to do the habit. This makes the app useless for important things that need reliable records e.g. a medication log to provide a doctor.

Honestly I'm not what the devs were thinking. There should be an **explicit NO** option. You should not select a choice by default. Preserve the difference between 'no record' and 'negative record'. E.g. cross mark, a dot, and a check mark as three states.

**Comment by iSoron** [comment] 2020-07-02 12:04
Closing this as a duplicate of #96.

**Closed by iSoron** 2020-07-02 12:04 UTC
