### ISSUE TITLE
App crash on select field

### ISSUE THREAD

**Issue by lascimmia** [iSoron/uhabits#935] opened 2021-05-28 14:36 UTC
## Description
On yes/no habit, the app crashes on frequency selection. 

## Steps to reproduce
1. Go to new habit
2. Click on frequency selection field

## System information
 - Phone: Xiaomi Mi 9 Pro
 - Phone Operating System: Android / Miui12

**Comment by iSoron** [comment] 2021-05-28 15:43
Thank you for the bug report, @lascimmia. I am closing this issue as it does not contain the app version, which is a necessary piece of information. If you provide it, I can reopen. If you are using Loop 2.0.1, this is a duplicate of #926; please upgrade to 2.0.2.

**Closed by iSoron** 2021-05-28 15:43 UTC
