### ISSUE TITLE
Habit Groups

### ISSUE THREAD

**Issue by YohananDiamond** [iSoron/uhabits#457] opened 2019-01-19 22:12 UTC
This feature could be something like **Fabulous**'s rituals. They would be a collection of habits to be done on a specific time / day.
They can be seen on the list just like normal habits (with a group signifier somewhere). When clicking on a day on its row, it would open a window showing all habits of that group.
To show that a habit group have been completed, it should show a completion mark (just like habits). But, if the user completed 1 or more habits but not all, instead of a completion mark, there could be a dash (-) instead.

This should not be confused with habit categories -- that's a whole another concept.

**Comment by YohananDiamond** [comment] 2019-01-19 22:20
Oh, I have realized that this is basically the same thing as the **Time Blocks** from issue #394

**Comment by iSoron** [comment] 2019-08-13 22:43
Duplicate of #495

**Closed by iSoron** 2019-08-13 22:43 UTC
