### ISSUE TITLE
Please allow numeric habits

### ISSUE THREAD

**Issue by jt007** [iSoron/uhabits#399] opened 2018-04-14 12:06 UTC
It's not allways just a "done" or not.

E.g:
How many hours reading/studying
How many hours on computer or phone (easy to get tracked automatic by anti-distraction apps)
How many friends contacted 
How many times taking vitamins/pills
etc etc....

For numeric habits it will be useful to be able to set a goal for the habit. This will be the requirement for the habit to be marked as done in the statistics:

E.g: "More than" or "less than"  [number]   per "day" or "week"

It's practical to have the week option (last 7 days), because then it's possible to get rewarded for more than one day if doing very much more than required certain days. When measured by last week, all numbers count, even if more or less compare to the goal. (E.g: If reading 1 instead of 2 hours, now it's just "not done", instead of contributing to the weekly goal).

**Comment by iSoron** [comment] 2018-04-14 12:46
Thank you for the suggestion, @jt007, but this is a duplicate of #42.

**Closed by iSoron** 2018-04-14 12:46 UTC
