### ISSUE TITLE
Stacked Checklist on Android 13 Not Checking Habits Off

### ISSUE THREAD

**Issue by sstewart122** [iSoron/uhabits#1611] opened 2023-01-02 02:01 UTC
## Pre-submission checklist
- [ x] I am submitting a bug report, not a feature request.
- [x ] I have searched for similar issues, but did not find any matches. - 
- 

> **Nothing open. Found an old one marked as closed, but issue is not resolved.** 

## Description
When using the stacked checklist widget, it will not actually check things off. Nothing happens when you hit the button to check off. Only happens in when habits are stacked. If they are single habits it will work fine. 

## Steps to reproduce
1. Have a checklist widget added and select multiple habits to create a stacked checklist 
2. When you try to check off a habit, Nothing happens

## System information
 - Phone: Samsung S22
 - Phone Operating System: Android 13
 - App version: 2.0.3

## Screenshots
![Screenshot_20230101_180056_One UI Home](https://user-images.githubusercontent.com/121777309/210190603-fa86ec3b-ea75-4097-b008-3ab3203a3a5f.jpg)

**Comment by iSoron** [comment] 2023-01-02 11:42
Duplicate of #1463

**Closed by iSoron** 2023-01-02 11:42 UTC
