### ISSUE TITLE
[Feature suggestion] Number habits

### ISSUE THREAD

**Issue by dvt32** [iSoron/uhabits#187] opened 2016-10-03 20:15 UTC
Will this be possible like it is in HabitBull (basically a habit that you don't directly "check off", but you log how many repetitions you've done of a certain behavior beforehand)?

**Comment by vossad01** [comment] 2016-10-03 22:30
Would #42 provide what you are looking for?

**Comment by iSoron** [comment] 2016-10-04 10:13
Duplicate of #42

**Closed by iSoron** 2016-10-04 10:13 UTC
Labels: duplicate
