### ISSUE TITLE
Feature Request: Schedule Backup

### ISSUE THREAD

**Issue by trymeouteh** [iSoron/uhabits#381] opened 2018-02-28 22:53 UTC
A cool feature would be to choose how often it will do a backup and export a .db file.

To also prevent having hundreds of backups taking up space you can have an setting to always overwrite the schedule backup file. This way you could have an hourly, daily, weekly backup automatically.

**Comment by iSoron** [comment] 2018-03-10 20:30
Thank you for the suggestion. This is a duplicate of #178.

**Closed by iSoron** 2018-03-10 20:30 UTC
