### ISSUE TITLE
Custom frequency not editable

### ISSUE THREAD

**Issue by McCio** [iSoron/uhabits#970] opened 2021-06-06 13:15 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
In the 1.x version of the app, it was possible to define custom frequency, like _2 times in 4 days_.
From version 2.x, it is working correctly with already-defined habits, but it is not possible to edit them without losing the custom frequency, nor it is possible to create new ones.

That was really useful because having a frequency of _2 over x days_ can encode _at most x-2 consecutive days without performing that habit_.

## Steps to reproduce
1. Install 1.x version
2. Create an habit with _2 over 4 days_ frequency
3. Update the app to 2.0.2
4. See it is shown as "2/4" in place of "every day" (top of the screen)
5. Click edit
6. See frequency is shown as "2/4"
7. Click to edit frequency
8. See "every day" is selected, and no option to specify custom frequency is available

[step 8 can be verified on its own]

## System information
 - Phone: OnePlus Nord
 - Phone Operating System: Android 11
 - App version: 2.0.2

**Comment by iSoron** [comment] 2021-06-06 17:17
Thank you for the feedback, @McCio. Please feel free to upvote and comment in #961 if you would like to see this feature returning. I am closing this issue as this was a deliberate change we made, and not a bug.

**Closed by iSoron** 2021-06-06 17:17 UTC
