### ISSUE TITLE
Add 3rd, partial completion option

### ISSUE THREAD

**Issue by ocwa1** [iSoron/uhabits#515] opened 2019-10-07 04:21 UTC
It'd be cool to add an option for a partially completed task.  A 3rd option, in-between completed and not completed.  There are days when I know I'm not going to get to a habit, despite any best efforts, so being able to mark it eliminates it from my to-do.  

Use cases include:
- You don't complete a habit because you were incapable or injured
- You don't have access to required equipment
- Mark habits you plan on skipping
- Vacation/travel days
- Anytime you plan on taking a break from a habit for a short period
- When you only partially complete a habit

**Comment by adrienbeau** [comment] 2019-10-07 13:38
It looks like your issue is a duplicate of issue #96.

**Comment by iSoron** [comment] 2019-10-07 14:39
Thank you for the suggestion, @ocwa1. As @adrienbeau points out, this is a duplicate.

**Closed by iSoron** 2019-10-07 14:39 UTC
