### ISSUE TITLE
5 times per week days are mixed up

### ISSUE THREAD

**Issue by oxr463** [iSoron/uhabits#706] opened 2021-01-12 00:56 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
The 5 times a week option is confusing. I was expecting to set up Mon-Fri reminders, but it seems like random days are selected.

## Steps to reproduce
1. Add Habit.
2. Set Repeat to 5 times per week.
3. Set Reminder to Monday - Friday
4. Save.

## Screenshots

![IMG_20210111_194959](https://user-images.githubusercontent.com/43783393/104255293-bc634b80-5446-11eb-86fa-ad37ce579eb8.jpg)

![IMG_20210111_195029](https://user-images.githubusercontent.com/43783393/104255308-c7b67700-5446-11eb-9a51-c7fbc70f8a81.jpg)

## System information
 - Phone: Motorola G7
 - Phone Operating System: Android 10
 - App version: 1.8.10

**Comment by iSoron** [comment] 2021-01-13 23:33
Hi @oxr463, the main interface always displays the last 5 days (counting down from today) for all habits, regardless of the habit frequency or reminders.

Closing this issue as the app is working as intended.

**Closed by iSoron** 2021-01-13 23:33 UTC
