### ISSUE TITLE
Calendar week

### ISSUE THREAD

**Issue by marieen** [iSoron/uhabits#708] opened 2021-01-13 22:42 UTC
Still having issues with calendar week, even tried to uninstall and reinstall on Monday to try somehow bypass that issue. The example habit is set to once a week, but it is not taking into account calendar week. Is there a way to choose between calendar week and in 7 days, or better X times in a week / X times in 7 days. Perhaps in settings could be chosen the mode it works and shows strikes.
![Screenshot_20210114-003445_Habits](https://user-images.githubusercontent.com/77417213/104518672-bc0eb000-5600-11eb-905d-fdf76dca6260.jpg)
![Screenshot_20210114-003436_Habits](https://user-images.githubusercontent.com/77417213/104518686-c335be00-5600-11eb-8278-8eaefa3f06ff.jpg)

**Comment by iSoron** [comment] 2021-01-13 23:28
> Is there a way to choose between calendar week and in 7 days, or better X times in a week / X times in 7 days.

@marieen Loop always use rolling intervals, not calendar weeks. Please feel free to open a feature request in our [discussion forum](https://github.com/iSoron/uhabits/discussions) proposing this feature. Closing this issue as it's not a bug.

**Closed by iSoron** 2021-01-13 23:28 UTC

**Comment by gappleto97** [comment] 2021-08-16 19:10
Is this also true of the numeric habits? The bars at the top seem to indicate otherwise
