### ISSUE TITLE
unable to see task icons in app

### ISSUE THREAD

**Issue by alexjo82** [iSoron/uhabits#843] opened 2021-03-12 19:13 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
recent eye injury impact my vision. i switch to dark mode to help use this app but the icons for task blend in with background, double tried light mode and similar. light mode though hurts my eyes right now too

## Steps to reproduce
1. turn on dark mode
2. look at icons
3. try light mode again
4. look at icons

## System information
 - Phone: [e.g. Google Pixel 4] nexus 5
 - Phone Operating System: [e.g. Android 10] android 6
 - App version: [e.g. 1.8.9] 1.8

**Comment by iSoron** [comment] 2021-03-12 20:45
Duplicate of #413

**Closed by iSoron** 2021-03-12 20:45 UTC
