### ISSUE TITLE
Widget for God's View

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#154] opened 2016-08-04 10:49 UTC
(Translating some user feedback from Google Play Store)
...Everything's good. But widget doesn't show several habits.
If widget presents habits like Main View of the app,
it's be much easier to grok many habits in a glance.

**Comment by iSoron** [comment] 2016-08-06 12:12
Hi Josh, thank you for translating these. This is a duplicate of #45.

**Closed by iSoron** 2016-08-06 12:12 UTC
