### ISSUE TITLE
Please add several times a day habits

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [iSoron/uhabits#436] opened 2018-08-30 23:58 UTC
like Tickmate does, but it's not material, ugly and dead

I'd like to clear teeth twice a day (with two reminders)
I'd like to count how much cakes I've eat in a day

**Comment by chennemann** [comment] 2019-01-20 08:11
I very much like this idea. But how should a part success be handled? 

If you did one of three repetitions should it be counted as success or failure. Also how should we indicate a partly success?

**Comment by iSoron** [comment] 2019-01-22 23:09
This is a duplicate of #121. Let's discuss it there.

**Closed by iSoron** 2019-01-22 23:09 UTC
