### ISSUE TITLE
series  identification issue

### ISSUE THREAD

**Issue by lgasp** [iSoron/uhabits#340] opened 2017-09-29 08:14 UTC
![_20170929_100412](https://user-images.githubusercontent.com/3661279/31006635-be462a40-a4fd-11e7-99d1-65e7454f9710.JPG)

With  latest f-droid  loop version, 1.7.6  I found an issue with entries on Monday, maybe.

For example, if I have a twice a week habit, and one entry is on **Monday**, (while the other is on another day of the same week), it doesn't consider it as good for the series identification.

In the attachment you can see that I have an entry on Monday, 18th of September, and the series is interrupted on the next Monday (25th of september), even if I had 2 entries in that week. If I change the entry from Monday to Tuesday (18th to 19th) everyithing is good again.

**Comment by iSoron** [comment] 2017-10-27 01:34
Thank you for the bug report, @lgasp. This is a duplicate of #124.

**Closed by iSoron** 2017-10-27 01:34 UTC
