### ISSUE TITLE
Numerical habits with target value 0 cause app to crash

### ISSUE THREAD

**Issue by mahdi1234** [iSoron/uhabits#903] opened 2021-05-11 19:35 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description

I couldn't install 2.0.1 over 2.0.0 so I first removed 2.0.0. and then installed loop-2.0.1-debug.apk and imported backup.

It crashed during restore and crashes on start-up.

Removing 2.0.1 and switching back to 2.0.0 it can be restored fine.

Crash report here - https://del.dog/cenguxipoc.txt

If you need backup to reproduce please contact me via PM I don't want to post it publicly.

**Comment by iSoron** [comment] 2021-05-12 02:14
Thank you for the bug report, @mahdi1234. If we had a copy of your backup file, it would indeed be much easier for us to reproduce this bug. Please feel free to send it to <dev@loophabits.org>. I won't share it with anyone.

**Comment by mahdi1234** [comment] 2021-05-12 09:37
Backup sent over email fyi @iSoron

**Comment by iSoron** [comment] 2021-05-16 01:06
Thank you for the backup, @mahdi1234. I was able to reproduce the issue. This will be fixed in Loop 2.0.2. The problem was that the app was not correctly handling numerical habits with target value of zero.

A workaround for importing your data into Loop 2.0.1 is changing all target values to something other than zero.

**Comment by iSoron** [comment] 2021-05-22 00:44
FIxed in branch `hotfix/2.0.2`

**Closed by iSoron** 2021-05-22 00:44 UTC
Labels: bug, confirmed
