### ISSUE TITLE
Count for habits

### ISSUE THREAD

**Issue by Shriyanshagro** [iSoron/uhabits#247] opened 2017-01-23 20:03 UTC
Let's say how many cigarettes did you smoked today?? 
Use Case :- When user wants to reduce the number of cigarettes per day.

Outcome needed - counter based habits

**Comment by iSoron** [comment] 2017-01-24 03:37
Unless I am missing something, this is a duplicate of #42. Please, feel free to post any feedback about this feature under that issue.

**Closed by iSoron** 2017-01-24 03:37 UTC
