### ISSUE TITLE
loophabits.org front page is blank

### ISSUE THREAD

**Issue by arschficken** [iSoron/uhabits#361] opened 2017-11-21 23:07 UTC
http://loophabits.org/ returns an empty page. According to archive.org, this has been the case since at least April 2016.

Instead, the front page should say something about the project, and link to the FAQ and GitHub page.

**Comment by uniqueid001** [comment] 2017-12-13 18:11
This is a duplicate of #267

**Closed** 2018-01-03 15:17 UTC
