### ISSUE TITLE
Dark mode unchecked items have low contrast

### ISSUE THREAD

**Issue by melocene** [iSoron/uhabits#719] opened 2021-01-22 16:53 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
In the app when using dark mode the checkmarks/X for incomplete days has a low contrast and can be tough to see. Light mode is better in this regard as they use a grey on a light background. To me it seems the color is the same for the incomplete marks between light and dark mode, and the grey background of the task is too similar. Trying the AMOLED did not seem to change either color.

The color for tasks can be customized, and the completed marks use the same color, but I am also not seeing a way to customize other colors in the app.

## Steps to reproduce
1. Add a task
2. Enable dark mode
3. Observe the marks for incomplete activity

## System information
 - Phone: Pixel 4a
 - Phone Operating System: Android 11
 - App version: 1.8.11

**Comment by hiqua** [comment] 2021-01-22 17:08
Duplicate of https://github.com/iSoron/uhabits/discussions/413

**Comment by iSoron** [comment] 2021-01-24 23:50
Thank you for report @melocene, but this is expected app behavior, not a bug. Please feel free to upvote the feature request linked by @hiqua if you would like to see changes to the theme.

**Closed by iSoron** 2021-01-24 23:50 UTC

**Comment by melocene** [comment] 2021-01-25 16:16
I am not sure I agree with it being a feature request as this is an issue for those with light sensitivity, trouble seeing shades of grey, or are otherwise visually impaired and trying to use the app.

The idea behind this issue was to just suggest a small change to the icon contrast to make it more visible, not a request for an overhaul of the theme, or add additional settings.

I see the linked feature request, and actually found another in the discussions, showing there is need for this. Since you note it as intended, would it be possible to get more context as to why this is designed as it is vs being more accessible for the visually impaired users?
