### ISSUE TITLE
Keep track of other metrics of a habit?

### ISSUE THREAD

**Issue by truvaking** [iSoron/uhabits#555] opened 2020-02-11 10:04 UTC
Hello. I haven't been able to have the right keywords for my particular issue so apologies if this was already discussed.

I was thinking if it would be a good idea to provide an optional feature where one can track other metrics of a habit? I'm mostly thinking about how long that habit took, or the quantitative or ordinal outcome of it. For example, one could input how many sketches they drew, or how many push ups they did, or how close to 6 a.m. they woke up. 

If that wasn't discussed, or was discussed and its plausibility and utility have not been denied, I'd love to contribute and implement that feature.

**Comment by KopfKrieg** [comment] 2020-02-15 15:34
I've got the same question and also found issue #42 which seems to solve your problem.

**Comment by iSoron** [comment] 2020-02-21 00:16
Thank you for the feedback. This is a duplicate of #42.

**Closed by iSoron** 2020-02-21 00:16 UTC
