### ISSUE TITLE
skipping a measurable habit enters 3

### ISSUE THREAD

**Issue by sphuo5g** [iSoron/uhabits#1760] opened 2023-07-13 20:18 UTC
## Description
Using a 'measurable' habit and choosing 'skip' from the popup puts in '3' instead of skipping that day. Additionally, unlike with 'yes/no' habits, there is no way of getting it back to '?' either.

## Steps to reproduce
1. Create a new habit of type 'measurable', put in some name and any target value (i.e. 1 or 100).
2. Back in the main view, tap or hold a day of that habit to change its value.
3. Choose skip.
4. Notice the day not actually getting skipped, but instead being counted as if you had put in 3.

## System information
 - Phone: Google Pixel 4a
 - Phone Operating System: LOS, Android 13
 - App version: 2.1.2

**Comment by iSoron** [comment] 2023-07-13 20:21
Duplicate of #1726

**Closed by iSoron** 2023-07-13 20:21 UTC
