### ISSUE TITLE
decimal separator «,» not usable after edit

### ISSUE THREAD

**Issue by erik55** [iSoron/uhabits#1781] opened 2023-08-05 23:22 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When I enter a numerical value that has decimals, I try to do this with a comma (e.g. 4,5) as this is how it works here. But: Not possible, comma can’t be entered in the text field. So I try it with a dot (e.g. 4.5). This works, great. It however **shown with a comma**! Which is great, better than nothing. BUT: When I want to edit/change/correct this value, I tap on it. Now the value is shown **with comma** (e.g. 4,5). If I only want to change the decimal place (e.g. to the value 4,6), I can do that. If I hit the save button, it is **NOT** saved, shows the old value again (e.g. 4,5).

## Steps to reproduce
1. Enter a decimal value in a task (for example how many minutes have you spent doing something today): It **has to be with a dot**, as a comma can not be entered.
2. Save it, works. But it is shown with a comma now (which is correct for my region).
3. Tap on it, to edit it.
4. Change any number.
5. Save it. **It does NOT work**. The old value is shown as the saved value.

## System information
 - Phone: Samsung Galaxy S9
 - Phone Operating System: Android 10
 - App version: 2.1.1

## Proposal for solution
* Allow entering of comma. Convert it to a dot (internally).
* Or don’t show/convert it to a comma.

**Comment by iSoron** [comment] 2023-08-31 18:15
Duplicate of #1719. Fixed in Loop 2.1.3.

**Closed by iSoron** 2023-08-31 18:15 UTC
