### ISSUE TITLE
Cannot insert decimal point in v.2.1.2

### ISSUE THREAD

**Issue by Aldo-cav** [iSoron/uhabits#1719] opened 2023-06-03 06:17 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
With previous version 2.1.1 I was able to insert numbers with decimal point, in v.2.1.2 the keyboard does not permit to enter comma or point, so have to insert only integer values.

## Steps to reproduce
1. Create an habit that ask for a numerical value
2. Try to insert a non integer value
3. does not work

## System information
 - Phone: Samsung Galaxy S10e
 - Phone Operating System: Android 12
 - App version: 2.1.2

**Comment by iSoron** [comment] 2023-06-04 22:42
Thanks for the bug report, @Aldo-cav. I cannot reproduce it on my phone or emulators. Could you please share a screenshot of the keyboard you are getting? It should include a dot/comma.

**Comment by LeicesterTriangle** [comment] 2023-06-05 06:52
I can reproduce the error. System setting are Germany, which means the decimal separator is the comma, & the thousands separator ist the period. 
The keyboard shows the following in the rightmost column, from top to bottom: Backspace thing (x in a leftarrow box), "OK, ".-" , and a greyed-out comma. It's not possible to enter X.y via the keypad, but it is possible to enter it via the clipboard.
(Sorry, no screenshot, I downgraded -- and F-Droid didn't revert, but threw an error, so backup/uninstall/reinstall 2.1.1/restore...)

Samsung A51, Android 13, error occurred with 2.1.2. but not with 2.1.1

**Comment by Aldo-cav** [comment] 2023-06-06 04:56
> Thanks for the bug report, @Aldo-cav. I cannot reproduce it on my phone or emulators. Could you please share a screenshot of the keyboard you are getting? It should include a dot/comma.

As @LeicesterTriangle said, maybe the issue is related to system setting, my phone is with italian language. Here the screenshot. 

[https://i.postimg.cc/9f1WZZ1R/photo-2023-06-06-06-44-30.jpg](https://i.postimg.cc/9f1WZZ1R/photo-2023-06-06-06-44-30.jpg)

**Comment by Aldo-cav** [comment] 2023-06-06 04:57
> Thanks for the bug report, @Aldo-cav. I cannot reproduce it on my phone or emulators. Could you please share a screenshot of the keyboard you are getting? It should include a dot/comma.

As @LeicesterTriangle said, maybe the issue is related to system setting, my phone is with italian language. Here the screenshot. 

[https://i.postimg.cc/9f1WZZ1R/photo-2023-06-06-06-44-30.jpg](https://i.postimg.cc/9f1WZZ1R/photo-2023-06-06-06-44-30.jpg)

**Comment by Aldo-cav** [comment] 2023-06-06 05:01
Sorry, closed by mistake!

**Comment by iSoron** [comment] 2023-07-08 23:05
Fixed in f1d3cd3 and should become available in Loop 2.1.3.

**Closed by iSoron** 2023-07-08 23:05 UTC
Labels: bug, cant-reproduce
