### ISSUE TITLE
crash when rating the app

### ISSUE THREAD

**Issue by anlalalu** [iSoron/uhabits#532] opened 2019-12-23 08:23 UTC
###### Reproduction Steps

1. tap 'more options'
2. tap 'About'
3. tap 'Rate this app on Google Play'

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.isoron.uhabits, PID: 3372
                                                 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=org.isoron.uhabits }
                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
                                                     at android.app.Activity.startActivityForResult(Activity.java:3424)
                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
                                                     at android.app.Activity.startActivityForResult(Activity.java:3385)
                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
                                                     at android.app.Activity.startActivity(Activity.java:3627)
                                                     at android.app.Activity.startActivity(Activity.java:3595)
                                                     at org.isoron.uhabits.activities.about.AboutScreen.showRateAppWebsite(AboutScreen.java:57)
                                                     at org.isoron.uhabits.core.ui.screens.about.AboutBehavior.onRateApp(AboutBehavior.java:57)
                                                     at org.isoron.uhabits.activities.about.AboutRootView.onClickRate(AboutRootView.java:85)
                                                     at org.isoron.uhabits.activities.about.AboutRootView_ViewBinding$3.doClick(AboutRootView_ViewBinding.java:60)
                                                     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                     at android.view.View.performClick(View.java:4438)
                                                     at android.view.View$PerformClick.run(View.java:18422)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Screen Shot

![screen shot](https://user-images.githubusercontent.com/46981872/71345491-7b309d00-25a0-11ea-892e-1b8f9d27ccb0.png)

###### Debug info
App Version = 1.7.11(dev)

Android Version = 4.4.4

**Comment by iSoron** [comment] 2019-12-29 11:16
Thank you for the bug report. This is a duplicate of #354.

**Closed by iSoron** 2019-12-29 11:16 UTC
