### ISSUE TITLE
When I Set habit to happen every week, It won't display correctly 

### ISSUE THREAD

**Issue by vivekkpatel** [iSoron/uhabits#1295] opened 2022-02-13 12:31 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [ ] I have searched for similar issues, but did not find any matches.
 

## Description
 I want to do something once a week, every week. 
So, I want to setup habit that i have to check only once in whole week and i'm done for whole week.
Check screenshot in below. See Last week I want to display colours to whole week, similar to previous 2 weeks.

## System information
 - Phone: OnePlus 6 
 - Phone Operating System:  Android 11
 - App version:  2.0.3

## Screenshots
![image](https://user-images.githubusercontent.com/60865708/153753070-60f9832f-6d16-4476-ad2a-d9fb9196f207.png)

**Comment by hiqua** [comment] 2022-02-13 14:06
Yes the "every week" option is a misnomer, it's every 7 days.

**Comment by vivekkpatel** [comment] 2022-02-13 14:56
any workaround to get what i want?

**Comment by iSoron** [comment] 2022-03-22 06:40
@vivekkpatel If you keep doing your habit exactly one day per week, but on different days, Loop will eventually fill up all the gaps. For example, if you add one repetition on Feb 14, then days Feb 7-12 will receive automatic checkmarks.

I am closing this issue as it is not a bug; the app is behaving as expected.

**Closed by iSoron** 2022-03-22 06:40 UTC
