### ISSUE TITLE
The 'dev' branch cannot import data from the stable version (missing DB index)

### ISSUE THREAD

**Issue by llunak** [iSoron/uhabits#327] opened 2017-09-11 13:52 UTC
The current dev branch is unable to import exported data from the stable version from Google Play. The import fails because of database upgrade from version 17 to 22, and the "drop index idx_repetitions_habit_timestamp;" command in 22.sql results in an exception because there is no such index in the DB file (as far as I can tell). The only other reference to this index is in 13.sql, but I presumably started using the app only when version 13 was already obsolete.

Besides this being somewhat annoying when working on the development version, and being a problem when the next version is marked stable, this also means that new users of the current stable version use DB setup without the DB index, possibly resulting in poor performance.

**Comment by iSoron** [comment] 2017-09-13 12:22
Our database migration system works like this: if someone opens the app for the first time, all the scripts are executed, starting from `13.sql` until `22.sql`. If you already have been using the app for a while and your database is, say, version 17, then, after updating the app, scripts `18.sql` until `22.sql` will be executed. So, in principle, the index should be there.

Are you able to reproduce this bug with a clean install of the app? Could you try the following:

1. Install the stable version from Google Play
2. Clear the app data
3. Create a few habits and export the database
4. Install the `dev` version and try to import the database

**Comment by llunak** [comment] 2017-09-13 17:52
Yes, I can reproduce the problem following these steps. The exported database is at http://ge.tt/5ItM0Xm2 , but I'd expect that anyone should be able to reproduce the problem the same way.

I have already figured out that the .sql scripts is how database upgrading works, but that seems to be the case only for the 'dev' branch version of the app. In the 'v1.7.6' tag version (which I assume to be the stable one), I cannot find the place in the source where the .sql scripts would be run. I actually just as well cannot find the place where the database would be created, so it may be just me, but what I think is happening is that v1.7.6 only creates the dabatases somewhere (SQLite automagic?) without indexes and never runs the 13.sql-17.sql scripts.

**Comment by llunak** [comment] 2017-09-16 17:43
I'm now fairly certain that what I wrote above is correct. Version 1.7.6 uses ActiveAndroid, the .sql scripts are never run, and there's no sql index in its database setup.
My suggested fix should avoid the problem of the current version not handling 1.7.6's database.

**Comment by iSoron** [comment] 2017-09-21 12:03
> Version 1.7.6 uses ActiveAndroid, the .sql scripts are never run, and there's no sql index in its database setup

ActiveAndroid was suposed to run all the SQL scripts. I will have a look at this later, to figure out how did it happen. In any case, I have merged your pull request and the issue is now fixed. Thanks!

**Closed by iSoron** 2017-09-21 12:03 UTC
Labels: critical-bug, needs-info
