### ISSUE TITLE
Multiple Line Chart Widget  for "Habit Strength"

### ISSUE THREAD

**Issue by fted** [iSoron/uhabits#521] opened 2019-11-05 08:28 UTC
Could be cleaner to use the "Habit Strength" Widget if it could contain multiple Habit lines.
Currently have several charts for each habit but since axis are fixed a multi-line chart would be great! =)

**Comment by chrrris1987** [comment] 2020-02-03 18:42
I was thinking the same. I love the widgets, but they are all seperate at the moment. Would be nice to choose more habits (would not set it at all or 1 habit, but that you can choose). 
That way you can pair similair habits like sports together.

**Comment by iSoron** [comment] 2020-11-26 18:34
Duplicate of #51

**Closed by iSoron** 2020-11-26 18:34 UTC
