### ISSUE TITLE
Multiple habit checks

### ISSUE THREAD

**Issue by Querschlag** [iSoron/uhabits#83] opened 2016-04-21 16:44 UTC
Habit checks are currently recognized as 1 Bit states per day - either "checked" or "unchecked".
This fits most use cases of habit tracking, but doesn't allow to quantify.
Would it be possible to implement a kind of counter control to track the number of times a certain habit has been fullfilled per day, additionaly to the 1 Bit state?
The tracking type would be specified by the user when adding a new habit (eg. Multi-Check / Single-Check).

This would allow to quantifiy the number of occurances for habits like smoking or sexual intercourse for example.

**Comment by iSoron** [comment] 2016-04-21 20:38
This seems to be a duplicate of #42. Feel free to reopen the issue if I am mistaken.

**Closed by iSoron** 2016-04-21 20:38 UTC
