### ISSUE TITLE
Skip days not available for measurable habits

### ISSUE THREAD

**Issue by rancidfrog** [iSoron/uhabits#1316] opened 2022-03-06 21:41 UTC
Pre-submission checklist
• [x] I am submitting a bug report, not a feature request.
• [x] I have searched for similar issues, but did not find any matches.

Description

I created a measurable habit.
I also have skip days enabled.
There is no way for skipping measurable habit.

Steps to reproduce
• long pressing a measurable habit opens up ticker. Which only allows you to select a number.
There is no way to select skip, even though it is enabled in settings

System information
• Phone: oneplus 
• Phone Operating System: Android 11
• App version: 2.0.3

Screenshots
![](https://i.imgur.com/Yuhj9Ho.jpg)

**Comment by jakester76** [comment] 2022-03-06 23:30
I would also like to have the ability to skip measurable habits.

**Comment by iSoron** [comment] 2022-03-21 23:26
Closing as this is not a bug; the developers are aware that skips are not available for measurable habits.

**Closed by iSoron** 2022-03-21 23:26 UTC

**Comment by jakester76** [comment] 2022-03-22 00:53
Ok, thank you! 😁 Still a wonderful app!
