### ISSUE TITLE
Add remote storage

### ISSUE THREAD

**Issue by LuxoftAKutsan** [iSoron/uhabits#492] opened 2019-05-07 14:17 UTC
Would be nice to add ability for remote storage (NextCloud/Docker/ remote db server)
This will add ability to create web app, ios app, and sync habits across devices.

**Comment by hiqua** [comment] 2019-07-18 10:05
Seems to be a duplicate of #104, or is it not?

**Closed** 2019-07-23 15:50 UTC
