### ISSUE TITLE
No update of text on frontpage after editing

### ISSUE THREAD

**Issue by jt007** [iSoron/uhabits#390] opened 2018-03-14 10:49 UTC
Habit text on frontpage on Loop Habits is sometimes still not updated hours after the text was edited (edited habit text and changed color).  Does not help to close the app and reopen several times. 
The text and color was successfully edited at once on the graph page, and when opening the edit window, everything is also fine. But still not on the front page. 
 
Have experienced this severel times, but not every time. Why does it not update on front page?
Have also experienced slow update of checkmarks on frontpage if they are edited from the graph page.

Using Android 5.0.2, Samsung Alpha. Ps: tried now to reboot my phone, and then it finally updated. But it should not be necessary to reboot the phone every time... 

Thank you for your help:)

**Comment by iSoron** [comment] 2018-06-17 13:00
Thank you for the bug report. I believe this has been fixed in the development version of the app. If the problem is still there when version 1.8.0 becomes available, please let me know, and I will reopen this issue.

**Closed by iSoron** 2018-06-17 13:00 UTC
