### ISSUE TITLE
Automatically adds checkmarks to some habits, unable to mark these as incomplete.

### ISSUE THREAD

**Issue by Snicrofone** [iSoron/uhabits#1602] opened 2022-12-28 12:34 UTC
## Pre-submission checklist
- [ x] I am submitting a bug report, not a feature request.
- [x ] I have searched for similar issues, but did not find any matches.

## Description
Adds checkmarks without any action on only select habits, often the more consistent habits. These checkmarks look different, they are outlines. A screenshot is below. There is no way to mark these as incomplete or make the outline checkmark go away. Also, I seriously had to make a github to say this?

## Steps to reproduce
1. I don't know, it just adds them without action

## System information
 - Phone: Samsung A71
 - App version: 2.0.3

## Screenshots
![Screenshot_20221228_072943](https://user-images.githubusercontent.com/121555991/209812451-ef71e75f-6bd3-4f9b-a3eb-041e2ec25c22.jpg)

**Comment by iSoron** [comment] 2022-12-28 13:41
Closing as this is intended behavior. Please see FAQ.

**Closed** 2022-12-28 13:41 UTC
