### ISSUE TITLE
Export issues (app choice dialog, files not appearing on MTP, error message, characters have to be supported by the filesystem)

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#111] opened 2016-05-24 07:51 UTC
When exporting, it makes me select an app.  Today one is "e-mail", and the other is "Termux" (a terminal).  I chose Termux, and export failed.

I just want a quick way to copy it to my PC without any MitM. Exporting a single file to the internal storage available via MTP would be best (it is supposed to encrypted, unlike the SD card, and MTP via jmtpfs+Vifm takes multiple seconds per file).

**Comment by licaon-kter** [comment] 2016-05-24 08:03
Android version?

If you install someting like https://play.google.com/store/apps/details?id=org.openintents.filemanager can you save it?

**Comment by aleksejrs** [comment] 2016-05-24 08:08
Android 5.1.

The only options now are Termux, Bluetooth, and Email.

CSV export just fails after a few seconds.

**Comment by aleksejrs** [comment] 2016-05-24 08:14
With Termux, a dialog box appears:

`Save file in ~/downloads/`
`[_______________]`
`[Open folder]  [Cancel] (in the system language) [Edit]`

I entered “223” into the input field, pressed “`Open folder`”, and got a dialog box from Termux:

`The following file does not exist: $HOME/bin/termux-file-editor`
`Create this file as a script or a symlink - it will be called with the received file as only argument.`
`[OK]`

**Comment by aleksejrs** [comment] 2016-05-24 08:20
(I do have OI File Manager installed)

**Comment by licaon-kter** [comment] 2016-05-24 08:36
Works with TotalCommander.

Anyway I guess [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html) needs to be implemented in SDK>=19  ( intent ACTION_OPEN_DOCUMENT ) and intent ACTION_GET_CONTENT on lower than 19..

**Comment by iSoron** [comment] 2016-05-24 11:19
You don't need an email app. Any app that is able to handle "application/zip" files should work. Google Drive and Dropbox, for example, work fine. If you don't want any of these, a copy of the file is also automatically saved on the SD card. Please see the FAQ.

I am not familiar with Termux, but the error you posted doesn't seem related to our app.

**Comment by licaon-kter** [comment] 2016-05-24 11:23
Any thoughts on what I've said? You'd be able to get the document interface and not depend on other apps being installed.

**Comment by aleksejrs** [comment] 2016-05-24 11:57
> a copy of the file is also automatically saved on the SD card.

When, exactly?  Maybe it is after the app is chosen, so that doesn't work if the app returns an error?

> Please see the FAQ.

A link to [the FAQ](http://loophabits.org/faq) in the README or a prominent copy of it in the source code would be useful.

**Comment by aleksejrs** [comment] 2016-05-24 12:07
I entered “`/`” into the input field, and the error message became `Error saving file: java.io.FileNotFoundException: /data/data/com.termux/files/home/downloads: open failed: EISDIR (Is a directory) [OK]`.

Then I entered something like “`/123`”, and the Termux terminal started, and nothing happened.

Should the directory exist on the SD card?  The CSV files with the working database is currently on the device.

**Comment by iSoron** [comment] 2016-05-24 12:09
@licaon-kter Are you suggesting that we implement a document provider, or that we invoke ACTION_OPEN_DOCUMENT?

@aleksejrs The file is saved immediately before the app-chooser dialog is shown. When the dialog is appears, just press the back button to close it. A file will be saved inside the folder `Android/data/org.isoron.uhabits/files/`. You don't need to have Termux installed.

**Comment by licaon-kter** [comment] 2016-05-24 12:37
Invoke.

Point of reference for me: https://github.com/M66B/NetGuard/ `Menu->Settings->Export...` and see what happens

**Comment by aleksejrs** [comment] 2016-05-24 12:51
> A file will be saved inside the folder `Android/data/org.isoron.uhabits/files/` on the SD card.

The `/files/` part (not in FAQ) is helpful, by the way.

Now I took the SD card out and put it into a card reader, and there are 6 .db backups and an incomplete (not enough directories) CSV backup.

**Comment by aleksejrs** [comment] 2016-05-24 12:55
A question about the CSV database.

It contains some repetitions:

```
001 MyHabit
002 AnotherHabit
003 MyHabit
004 DifferentHabit
005 YetAnotherHabit
```

Could that be caused by copying from the SD card onto the device?  Maybe I copied both the real database and a backup, and they had different numbers for the habits?

**Comment by aleksejrs** [comment] 2016-05-24 12:57
It's a 64 GB SDXC card with FAT32 in a smartphone that officially (according to all Russian shops and reviews) supports up to 32 GB.

**Comment by aleksejrs** [comment] 2016-05-24 13:16
> Now I took the SD card out and put it into a card reader, and there are 6 .db backups

The files appear immediately in OI File Manager, but on MTP, they didn't even after a reboot of the device.  Maybe it's a bug somewhere like libmtp.

**Comment by iSoron** [comment] 2016-05-24 16:07
@licaon-kter Thank you for the suggestion. I have created a new issue for this (see #112). Pull requests are very welcome, as always.

**Comment by iSoron** [comment] 2016-05-24 16:10
> New files appear immediately in OI File Manager, but on MTP, they didn't even after a reboot of the device. Maybe it's a bug somewhere like libmtp.

@aleksejrs This is an old bug in Android. See this [StackExchange][1] question, for example.

> incomplete (not enough directories) CSV backup
> It contains some repetitions:

Are you sure that the app is generating CSV archives with missing or duplicate habits? Could you please try to delete all the files and start again from scratch? Could the duplicate habit you see be actually an archived habit that you forgot you have?

[1]: https://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp

**Comment by aleksejrs** [comment] 2016-05-24 19:32
> Are you sure that the app is generating CSV archives with missing

I am sure I have many more habits in my app than there are in the CSV backup on the SD card.  The CSV backup contains only 13 and no duplicates.  The Habits.csv file has 47 lines.

> or duplicate habits?

As the “real” Habits.csv has 34 lines and there are 33 directories, I guess they are not duplicate but misnamed.

> Could you please try to delete all the files and start again from scratch?

Tomorrow, if you still need it.

> Could the duplicate habit you see be actually an archived habit that you forgot you have?

How to archive a habit, and how to find out if a habit is archived?  Checking “Show archived” doesn't seem to make any difference.

**Comment by aleksejrs** [comment] 2016-05-24 19:35
I have several habits with “`:`” in their names, and none of the directories have names related to them.

**Comment by aleksejrs** [comment] 2016-05-24 19:36
IIRC, FAT does not support “`:`” in file names.  I thought Android used ext4 for its internal memory though.

**Comment by aleksejrs** [comment] 2016-05-24 19:48
> I am sure I have many more habits in my app than there are in the CSV backup on the SD card. The CSV backup contains only 13 and no duplicates. The Habits.csv file has 47 lines.

The 14th habit in Loop has a “`/`” in its name.

**Comment by licaon-kter** [comment] 2016-05-24 20:14
@aleksejrs Why not edit your post instead of making new ones?

**Comment by aleksejrs** [comment] 2016-05-25 07:42
@licaon-kter Maybe somebody is reading the emails, and they wouldn't get the updates.

**Comment by licaon-kter** [comment] 2016-05-25 08:53
I agree, but now you're basically spamming us all. :-1:

**Comment by iSoron** [comment] 2016-05-25 14:03
@aleksejrs Thank you for reporting this bug. I have successfully reproduced it here. Since this discussion is already rather long, I have created a new issue for it (#113).

**Closed** 2016-05-27 12:28 UTC
Labels: question
