### ISSUE TITLE
Mark a day as Irrelevant / Not Applicable

### ISSUE THREAD

**Issue by adrienbeau** [iSoron/uhabits#406] opened 2018-05-02 17:53 UTC
I have been using Loop for a few months now, and am overall very pleased with its current features and simplicity.

However, as I finally enjoyed a few days off this past week, and eyeing towards a two-weeks vacation, I found myself stuck between a rock and a hard place when it comes to work-related and home-related habits. These are *irrelevant* during vacations, but Loop currently only allows one of the following:

- mark such habits as Done for the day; which is not correct, and feels very much like cheating;
- mark such habits as Not Done for the day; which is also incorrect, and feels unjustly crippling.

This is particularly important for habits that are hard to achieve. Besides, having to *think* about such work and home habits (are they done or not) during a vacation kind of defeats the purpose of being on a vacation. However, I do not want to "pause" all my habits at once, because I want to maintain some lifestyle-habits all year long.

So, it would be great if there was a **fourth state** for any given day (besides Done, Not Done, Implicitly Done): this could be called **Irrelevant** (or Not Applicable), and could be represented by a grey dash in the habits overview, and a white square in a habit history. A day in such a state would be fully ignored for score calculations, longest streaks, determining which days should be implicitly done, etc.

In terms of UX, this state could be set using the current long-press interface, cycling between three states (Done, Irrelevant, Not Done) rather than two. Since this might be puzzling to newcomers, and some people may want to avoid the temptation, maybe the whole feature should be off by default and activated in the app settings.

*Edit:* typos and wording refinements

**Comment by boughtonp** [comment] 2018-05-06 16:01
Came here to request basically the same feature.

I'm don't like the term "Irrelevant" for it though - either "Not Applicable" or "Ignored" would be better.

The ability to add a brief note explaining why would be nice, but not essential.

**Comment by iSoron** [comment] 2018-06-16 00:54
Thank you for the suggestion. This is a duplicate of #88.

**Closed by iSoron** 2018-06-16 00:54 UTC
