### ISSUE TITLE
Reminders are unreliable in some phones

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#160] opened 2016-08-09 12:04 UTC
I have a habit, that is due every week, with a reminder for weekends (Saturday and Sunday) on 10:00, but this reminder isn't showing up. Changing it solely to Monday makes the reminder appear again.

Any ideas why?

**Comment by iSoron** [comment] 2016-09-03 13:07
Thank you for reporting this issue. I have changed the title, since I think this problem is caused by something more general. I am planning to completely rework the way reminders are handled internally, in order to make them more reliable.

**Comment by vossad01** [comment] 2016-10-02 03:05
@sojusnik What version of Android are using?

I have not used reminders in Loop yet, but I have had many similar issues with other apps caused by "Doze" starting with Android 6 (Marshmallow).  If this is the case for you, "whitelisting" the app under Settings -> Battery -> Battery optimization may be a valid workaround.

**Comment by sojusnik** [comment] 2016-10-03 21:49
@vossad01 5.1.1.

**Comment by sojusnik** [comment] 2016-10-16 15:42
Maybe this additional information will help you eliminating this bug:

I checked my habit from the first post on the 9th of October, a Sunday. The reminder didn't appear on the next Saturday, the 15th of October, but only today, on the 16th of October, a Sunday.

**Comment by woj-tek** [comment] 2016-11-01 14:30
Sorry for the duplicated #200. @licaon-kter - to be honest while making some correlation to Doze I haven't exempted it from the list before - I've done it now and I'll observe if it helps.
However I have a couple of other applications relaying on notifications (CalendarNotificaionPlus) and it works without exempt.

**Comment by iSoron** [comment] 2017-03-23 01:57
@sojusnik I think the issue you described is unrelated from what I had in mind originally. If your habit is weekly and you added a checkmark on Sunday, then there will be a grey checkmark on the following Saturday. That is, the app thinks that you have already completed the habit for the week, and will not show you the reminder.

The issue I had in mind is that, for some phones, the app seems to get killed in the background and the reminders do not work at all.

**Comment by sojusnik** [comment] 2017-03-29 21:02
@iSoron I think, that my issue is the same as @woj-tek is describing [here](https://github.com/iSoron/uhabits/issues/263):

> I've noticed that if I mark the habit on weekend as well then I don't receive notification on the weekday (seems that if the requirement for habit is already fulfilled it disables notification?).

**Comment by iSoron** [comment] 2020-07-16 13:13
There are still a large number of users complaining that reminders are unreliable. This has been a persistent issue since the first version of the app, and is probably related to aggressive power saving modes in some phones. See [dontkillmyapp.com](https://dontkillmyapp.com/) and [this AOSP issue](https://issuetracker.google.com/issues/122098785).

In Loop 1.8.8, we now print a lot of debug messages related to reminders, which will hopefully help us understand this issue better. Ideally, after each startup, the app could identify that reminders were not shown when expected, while the app was in background, and at least alert the user that something is wrong with their phone.

**Comment by iSoron** [comment] 2021-01-03 17:57
Closing as this bug report lacks actionable information. If you are experiencing issues with the reminders and are willing to help the developers track down the problem, [please submit a new bug report](https://github.com/iSoron/uhabits/issues/new/).

**Closed by iSoron** 2021-01-03 17:57 UTC
Labels: bug, cant-reproduce
