### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by UjwalNK** [iSoron/uhabits#612] opened 2020-07-22 17:39 UTC
Please add a feature to categorize habits.
Such as Morning, Evening etc... And show the progress of the specific categories, also time each category /  set an alarm for each category

**Comment by KristianTashkov** [comment] 2020-07-22 21:06
Duplicate of https://github.com/iSoron/uhabits/issues/31

**Closed** 2020-07-25 13:56 UTC
