### ISSUE TITLE
Feature Request: Statistic graph for more than one habit

### ISSUE THREAD

**Issue by helio2k** [iSoron/uhabits#328] opened 2017-09-11 16:32 UTC
Hi everyone,

love the app so far!
But i think i have an interesting update/feature for the statistic graph:
I think it should be possible to show up to (depending on the size of the graph) 4 different habits in the same graph, and be able to tell the difference.
The different habits could pull its color which are assigned in the app.

You could get much more information about your habits with one glance.

**Comment by iSoron** [comment] 2017-09-13 12:08
I'm glad you like the app, @helio2k. This feature request is a duplicate of #51, so I am closing it.

**Closed by iSoron** 2017-09-13 12:08 UTC
