### ISSUE TITLE
No notifications after a habit is connected to Tasker

### ISSUE THREAD

**Issue by tadwohlrapp** [iSoron/uhabits#1536] opened 2022-10-06 10:18 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
I have five habits and one of them is connected with Tasker to check the habit once a NFC Tag is scanned (Think of 'brush teeth' or so, and the NFC tag is next to the toothbrush. Once scanned, the habit is marked completed for the day).

I have enabled reminders for all five tasks. Four reminders work fine, but the Tasker-enabled habit seems to have lost its ability to trigger a notification. Even after deleting everything in Tasker (as I stopped using NFC) the notifications didn't come back. Tried emptying cache and restoring DB but that didn't solve it.

## Steps to reproduce
1. Create a habit and enable reminders
2. Create some routine in Tasker and connect it to the habit
3. Notice that you don't receive notifications for this habit anymore

## System information
 - Phone: Google Pixel 5
 - Phone Operating System: Android 13
 - App version: 2.0.3

**Comment by iSoron** [comment] 2022-10-22 21:31
Thanks for the bug report, @tadwohlrapp, but I was unfortunately not able to reproduce it. Could you double check that all the habits actually have reminders, and that you have not completed the habit that day, prior to the notification showing up?

I am skeptical that this is related to Tasker, since we do not really "connect" a habit to Tasker; Loop knows nothing about your Tasker actions. The way the integration works is, during the configuration phase, Loop tells Tasker what the habit id is, then Loop completely forgets about it (we don't store anything related to Tasker in our database). Whenever Tasker wants to toggle a checkmark, Tasker sends an intent to Loop with the habit id and the checkmark state. This intent is actually identical to the one Loop sends to itself when you click the notification, for example, so we don't even know whether it's coming from Tasker or from ourselves.

Given this, I am closing this issue; but if someone else is having the same issue described, please let us know.

**Closed by iSoron** 2022-10-22 21:31 UTC
Labels: bug
