### ISSUE TITLE
Applications crashes from time to time

### ISSUE THREAD

**Issue by qv1x0te** [iSoron/uhabits#287] opened 2017-05-16 19:32 UTC
Hi, 

The version 1.7.0 of the application crashes from time to time in my device when re-opening it after some time idle. You can find attached a generated bug report with the details.

[Bug Report - Loop Habit Tracker.txt](https://github.com/iSoron/uhabits/files/1005615/Bug.Report.-.Loop.Habit.Tracker.txt)

**Comment by iSoron** [comment] 2017-05-17 22:45
Thank you for the bug report, @qv1x0te. This crash has already been fixed in the development branch (see 65cc99db). The next version of the app (version 1.7.1) should not suffer from this issue. If it does, please let me know.

**Comment by iSoron** [comment] 2017-05-24 19:28
I have confirmed that this issue is still there. The previous commit solved a very similar bug, but not exactly this one. This seems to be related to [a bug in the Android Support Library][1].

[1]: https://issuetracker.google.com/issues/37073849

**Comment by SiwyBoy** [comment] 2017-05-26 07:52
What I noticed:
1. Open the app
2. Click the Home button to leave the app. It stays in background. 
3. Wait till it's "closed" by system. On my device it happens after few minutes when the screen is turned off or when I use lot of memory consuming apps. I hope you understand what I mean ;) 
4. Try to open it. 
5. App crashes. 

When it won't crash? 
1. Open the app 
2. Click the Overview button
3. Slide to close the app
4. Next time it will open properly 

Regards 
Artur

**Comment by iSoron** [comment] 2017-05-28 12:48
I have uploaded a new version of the app (1.7.2) to Google Play, which should fix this problem (again). If you still experience this issue with the newest version, please let me know.

**Closed** 2017-06-01 00:45 UTC
Labels: confirmed, critical-bug
