### ISSUE TITLE
Google Play version stuck at 2.0.3

### ISSUE THREAD

**Issue by yegle** [iSoron/uhabits#1597] opened 2022-12-24 09:11 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
It looks like my Pixel 5 can only download a 2.0.3 version from the Play Store.

## Steps to reproduce
1. On my Pixel 5, go to https://loophabits.org
2. Click on the "Google Play" link
3. No newer version offered

## System information
 - Phone: Google Pixel 5
 - Phone Operating System: Android 13
 - App version: 2.0.3

## Screenshots
![Screenshot_20221224-011022](https://user-images.githubusercontent.com/146133/209429015-e62c47d7-addf-4338-b168-f9af3ab374bc.png)

**Comment by iSoron** [comment] 2022-12-24 09:51
Duplicate of #1522

**Closed by iSoron** 2022-12-24 09:51 UTC
