### ISSUE TITLE
Score & Streaks on Frontpage

### ISSUE THREAD

**Issue by HariprasadManimozhi** [iSoron/uhabits#1098] opened 2021-09-07 12:25 UTC
### Discussed in https://github.com/iSoron/uhabits/discussions/1097

<div type='discussions-op-text'>

<sup>Originally posted by **HariprasadManimozhi** September  7, 2021</sup>
Hi, 
The current front page could be improvised by adding the metrics - Score % and Streaks. This enables to have a quick overview of habit loops on the front page at a glance and keep up the habit loops.

Attached a sample screenshot of the feature. Kindly include this feature in the future roadmap.

<img src="https://user-images.githubusercontent.com/28645647/132343133-a04d9322-6249-4243-aaca-49d2be73e0dd.png" width="350" height="600">
</div>

**Comment by hiqua** [comment] 2021-09-08 19:20
Closed as dupe of https://github.com/iSoron/uhabits/discussions/1097, let's keep the discussion there!

**Closed by hiqua** 2021-09-08 19:20 UTC
