### ISSUE TITLE
Pin code protection 

### ISSUE THREAD

**Issue by akhater** [iSoron/uhabits#193] opened 2016-10-21 11:36 UTC
I would really love to have the ability to protect the APP with a PIN code so it would protect it when the phone is in the hands of anyone else

Cheers

**Comment by akhater** [comment] 2016-10-21 11:57
Sorry just did a search and noticed you have already decided not to implement this feature

Too bad but I respect your decision

**Comment by iSoron** [comment] 2016-10-22 16:21
Yes, this is a duplicate of #86

**Closed by iSoron** 2016-10-22 16:21 UTC
