### ISSUE TITLE
Option to hide habits not possible to do today

### ISSUE THREAD

**Issue by jt007** [iSoron/uhabits#402] opened 2018-04-20 07:50 UTC
I like the feature Hide habits completed today. 
Some habits are unfortunately not possible to complete today. It would be nice to be able to hide this/those habits just for today. So we can view only those habits that are relevant today.

One possible way to solve this: 
When long pressing the habit, we today get the options (in the menu up right corner):  archive or delete. Please add "hide today" on this list.

**Comment by jt007** [comment] 2018-04-20 17:26
Could it be possible to add this nice feature?

**Comment by iSoron** [comment] 2018-04-21 16:44
Duplicate of #272

**Closed by iSoron** 2018-04-21 16:44 UTC
