### ISSUE TITLE
bug when creating new habits

### ISSUE THREAD

**Issue by jeff92** [iSoron/uhabits#539] opened 2020-01-02 16:48 UTC
when I try to create a new habit it's name changes to a random habit I already created .
this mostly happens when I try to rearrange my new habit.

**Comment by iSoron** [comment] 2020-01-03 02:51
Thank you for the bug report, @jeff92. Does this happen consistently? If so, could you list the steps to reproduce it? Also, what version of the app are you using? You can see this information in the About screen.

**Comment by TheWithz** [comment] 2020-01-03 04:34
I had this issue as well. 
Getting the latest update from the playstore (I'm on the beta) fixes the issue. 

Pixel 2 XL
Android 10 December security patch
Loop beta 1.8.2

**Comment by TheWithz** [comment] 2020-01-03 04:42
Hmmm. Please disregard my previous comment. The issue is still occuring. When I create a new habit, it overwrites the previous habit rather than creating a new one. The name and question update, however, the streak stays. Which has the strange effect of also updating the widgets.

**Comment by iSoron** [comment] 2020-01-03 12:59
Thank you for the extra information, @TheWithz.

* Could you please generate a bug report from within the app after the problem occurs (Settings / Generate bug report)? Feel free to either attach it here, or to send it by email to me.
* If you could provide a screen recording of the bug happening, that would be very useful. You can use an app such as [ScreenCam](https://f-droid.org/en/packages/com.orpheusdroid.screenrecorder/), from F-Droid.
* Could you try to repair the database (Settings / Repair database) and see if the problem persists?

**Comment by TheWithz** [comment] 2020-01-03 14:04
Bug report and screen recording sent to `dev@loophabits.org`
I repaired the database before the screen recording and the problem persisted.

**Comment by iSoron** [comment] 2020-01-03 18:06
Thank you for the bug report, @TheWithz. Here is the relevant part of the stacktrace.

	01-02 23:39:47.586 23653 23653 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
	01-02 23:39:47.586 23653 23653 E AndroidRuntime:  ViewHolder 1:ViewHolder{98c66b6 position=2 id=2, oldPos=-1, pLpos:-1 not recyclable(1)}
	01-02 23:39:47.586 23653 23653 E AndroidRuntime:  View Holder 2:ViewHolder{426475f position=1 id=2, oldPos=-1, pLpos:-1} org.isoron.uhabits.activities.habits.list.views.HabitCardListView{f789de4 VFED.V.L. ......ID 0,364-1440,2614 #9}, adapter:org.isoron.uhabits.activities.habits.list.views.HabitCardListAdapter@845e245, layout:android.support.v7.widget.LinearLayoutManager@7108d9a, context:org.isoron.uhabits.activities.habits.list.ListHabitsActivity@e59abb
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.support.v7.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4058)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3982)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1877)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:407)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:722)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:883)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:100)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.os.Looper.loop(Looper.java:214)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7356)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	01-02 23:39:47.586 23653 23653 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by iSoron** [comment] 2020-01-05 14:38
@TheWithz @jeff92 Thank you for the bug report and for your cooperation in investigating this issue. A new beta version (1.8.6) will be published shortly on Google Play. When it becomes available to you, could you please download it and verify if it fixes the problem?

**Comment by TheWithz** [comment] 2020-01-17 18:54
After testing for a number of days, the issue appears to be fixed as of 1.8.6.

**Closed** 2020-01-20 12:11 UTC
Labels: bug, confirmed
