### ISSUE TITLE
Add a note when marking habit

### ISSUE THREAD

**Issue by foobarbazquxfred** [iSoron/uhabits#248] opened 2017-01-24 06:00 UTC
I think it would be useful if a user were able to add a note when marking a habit. For example, which book they're reading, or how much time they meditated, etc. It would be even nicer if numeric notes could be graphed.

**Comment by licaon-kter** [comment] 2017-01-24 06:58
Duplicate of #246 which is duplicate of #194

/Close

**Closed** 2017-02-03 02:49 UTC
