### ISSUE TITLE
Automatic Backup

### ISSUE THREAD

**Issue by r4taw2mg** [iSoron/uhabits#484] opened 2019-03-01 07:49 UTC
Please add an option to regularily back up data on a schedule (e.g. daily, weekly). Backup functionality is already part of the app, but I have to do it manually. It would be great, if one could choose, how many backups to keep.

**Comment by mrstlmk** [comment] 2019-03-01 08:40
Agreed. Good idea.

**Comment by pasbc** [comment] 2019-03-02 20:36
I too think that it would be a very useful feature. Just something that isn't overly complicated would suffice like syncing at whatever interval to Google drive or something similar

**Comment by iSoron** [comment] 2019-03-03 00:34
Duplicate of #178.

**Closed by iSoron** 2019-03-03 00:34 UTC
