### ISSUE TITLE
Add option to hide satisfied habits

### ISSUE THREAD

**Issue by skomorokh** [iSoron/uhabits#102] opened 2016-05-16 01:18 UTC
I'd like to use this software for some less frequent things, however I don't want to see them in the list immediately after completing them as they won't need doing for a while yet. 

For example, I want to maintain a habit of mopping the floor at least every 10 days. Once I've mopped the floor I'd like it to hide for 7 days. That way it doesn't clutter up the list when it doesn't need mopping, but it's available when it's getting close to a reasonable time for it.

**Comment by iSoron** [comment] 2016-05-16 13:45
Thank you for the suggestion. Since I am trying to keep the interface very simple, I am not very inclined to add yet another field such as "hide for x days", but we could certainly hide all habits that are already done for today.

**Comment by skomorokh** [comment] 2016-05-30 01:27
How about a single global setting for "If not due for more than X days, hide until Y days before due"? It'd be in the preferences and not cluttering up the per-item interface. 

Or even hardcoded to 7 and 2 would still be adequate to allow tracking of infrequent routines: "Hide all habits less frequent than weekly until two days before they become due"

**Comment by checketts** [comment] 2016-07-01 02:54
Instead of complicating it by trying to show a number of days out, how about a just a simple toggle that would display habits that still need to be completed (ie have an X for today)? Maybe it could be next to the 'Show Archived' option?

I have begun tracking many long term habits (or breaking them up into smaller ones). For example to stay on top of my Taekwondo forms I need to review them. I want to create a habit for each form to repeat every 10 days. 10 forms over 10 days, I realize could be kept as a single habit, but being able to see if I'm behind on a form, or if I want to put in extra practice for a single one, I can track it. 

That is the extreme example. Most of my other habits that are twice a week or that I've completed today, I'm ok hiding. And with it being a simple toggle it is easy to show all if I want to review them all.

![screenshot_2016-06-30-20-39-13](https://cloud.githubusercontent.com/assets/416063/16510407/f0c67694-3f02-11e6-98ae-14e6a7e9ee29.png)

**Comment by checketts** [comment] 2016-07-06 02:42
I just downloaded and built the project to see how difficult adding that filter would be and was super excited to see you already implemented it!

It works perfectly! Now it shortens my list of 30+ habits to just 4 I need to focus on. Thanks!

**Comment by iSoron** [comment] 2016-07-06 08:34
@checketts Note that the `dev` branch still has some bugs and performance regressions. I use it daily, but I wouldn't recommend it to most users yet.

**Comment by checketts** [comment] 2016-07-06 14:47
I understand. Unfortunately I'm not much help regarding Android code, I though I work daily with Gradle and Java making web services. I'm willing to overlook some of the bugs while using this feature. Would you like me to report any bugs I find? I'll post here on how using the filter feature works. 

For example I'll add some inverse goals that I check at the beginning of the day and un-check if I fail to keep it (Eat healthy daily). I suspect the filtering will be fine and not make working with that goal hard, since I'll see it in the morning, and check it committing to it and unfiltering/unchecking if I fail.

**Comment by iSoron** [comment] 2016-07-07 12:01
>  I'm willing to overlook some of the bugs while using this feature. Would you like me to report any bugs I find?

Sure. The filtering itself should work fine, but there are some glitches with the new animations on the list of habits. I'm currently working on them, so you don't need to report those. If you find other small bugs and you think you can fix them, feel free to submit a pull request. That would be very welcome.

> I suspect the filtering will be fine and not make working with that goal hard, since I'll see it in the morning, and check it (committing to it) and unfiltering/unchecking if I fail.

Yes, this will be an issue when we implement #125. The habits that receive a checkmark automatically would simply never appear on the list.

**Comment by iSoron** [comment] 2016-07-14 14:19
Closing this issue, since this feature has been implemented in the `dev` branch.

**Closed by iSoron** 2016-07-14 14:19 UTC
Labels: new-feature, normal-priority
