### ISSUE TITLE
Activity for viewing many habits at once

### ISSUE THREAD

**Issue by Invertisment** [iSoron/uhabits#396] opened 2018-03-25 06:38 UTC
For now I've used the app to monitor my daily activities.
It would be nice if I could see several habits on a single graph.
I would like to see multiple curves on the same habit strength canvas.
I would like to have a button at the top, near "add habit". That button would open up a new screen that has same graphs as in normal single habit screen. 
It should have list with all my habits and a checkbox near each of them. 
When I check any habit, the graph should update with the info. 
If I check two checkboxes then two lines should appear. 
Week, month and daily dropdown should be present as well.

History and best streaks of combined habits would be nice as well. It should possible to represent that as well by reducing all of the checkboxes into checked/unchecked days. And also that would be a separate calculation before plotting.

Note: 
If we implement this screen for all of the habits, it would be possible to implement it for habit groups as well. (https://github.com/iSoron/uhabits/issues/325)

Picture (pardon my phone paint skills):
![screenshot_20180325-095803_01](https://user-images.githubusercontent.com/1641263/37872595-8ca73b54-3013-11e8-941d-e96f31c67cd2.jpg)

**Comment by iSoron** [comment] 2018-04-14 14:29
Thank you for the suggestion, @Invertisment. This is a duplicate of #51.

**Closed by iSoron** 2018-04-14 14:29 UTC
