### ISSUE TITLE
Consolidated chart of all Habits in single page

### ISSUE THREAD

**Issue by zaheernathani** [iSoron/uhabits#635] opened 2020-09-07 02:12 UTC
Currently, Widget allows to see charts of single habit. There should be option to see all Habits chart in a single page.

**Comment by chennemann** [comment] 2020-09-07 09:15
Could you elaborate how that could be useful. I have more than 25 habits and seeing them in one graph would be everything but confusing and unorganized. 
Is there a specific use-case you need that aggregated view for?

**Comment by iSoron** [comment] 2020-09-07 14:09
This is a duplicate of #45 and #51.

**Closed by iSoron** 2020-09-07 14:09 UTC
