### ISSUE TITLE
Add Group By

### ISSUE THREAD

**Issue by matthewfcarlson** [iSoron/uhabits#437] opened 2018-08-31 19:03 UTC
Big fan of Habits, I've gotten a few friends hooked. I'd love to be able to group by color or frequency of habit (daily vs weekly) and then sort by another metric

**Comment by matthewfcarlson** [comment] 2018-09-04 16:31
I think I'll try and create a pull request that implements this feature

**Comment by iSoron** [comment] 2018-09-04 17:32
Hi @matthewfcarlson, I'm not sure I completely understand your proposed idea, but I would be very glad to review such a pull request. If you have any questions implementing this, just let me know.

**Comment by oraant** [comment] 2018-10-01 21:28
+1, too many item, want to show them in different ways group

**Comment by JuliaCastillo** [comment] 2019-01-05 11:19
I actually think that would be really helpful. At the moment I group the habits by using different colours, but I would love to be able to maybe create different groups (i.e. morning routine, before bed) and be able to collapse one of those groups, so it only shows the name of the group and not each habit.

**Comment by iSoron** [comment] 2019-08-13 22:44
Duplicate of #495

**Closed by iSoron** 2019-08-13 22:44 UTC
