### ISSUE TITLE
Add multiple times per DAY rule

### ISSUE THREAD

**Issue by injainja** [iSoron/uhabits#628] opened 2020-08-27 18:48 UTC
Really awesome. Only thing missing is doing tasks several times per DAY. Like: drink 8 glasses of water per day. Or: meditate 3 times per day. This could be achieved by not displaying a check mark when clicking, but a countdown and on the final click the checkmark. E.g.: eat fruit twice a day will not show '❎'  but '2' each day as default. After my first fruit '1' and after my second fruit '✅'. That would be perfect.

**Comment by iSoron** [comment] 2020-08-28 02:05
Duplicate of #42

**Closed by iSoron** 2020-08-28 02:05 UTC
