### ISSUE TITLE
Feature Request: User login with Google or social media

### ISSUE THREAD

**Issue by ShyvayChamanNarved** [iSoron/uhabits#506] opened 2019-08-30 13:27 UTC
It can help very much

**Comment by hiqua** [comment] 2019-08-30 17:05
Which login are you referring to? There's currently no login procedure in the app AFAIK.

**Comment by ShyvayChamanNarved** [comment] 2019-08-31 08:25
I like to login with Google Account in this app so i can see my account or habits in another device.

**Comment by hiqua** [comment] 2019-09-01 21:47
Ok so unless I'm mistaken, this looks like a duplicate of #104.

**Closed** 2019-09-15 20:25 UTC
