### ISSUE TITLE
Feature request: categories/grouping

### ISSUE THREAD

**Issue by o-antsiferov** [iSoron/uhabits#325] opened 2017-09-08 13:34 UTC
It would be great to have categories or some kind of grouping for similar habits.

**Comment by konahart** [comment] 2017-09-08 20:57
I would love this. It would be nice to 
a) view a particular set of habits at a time (e.g., everything related to Health) and 
b) be able to have a meta-habit representing the group that gets checked if anything in the group is checked (e.g., if "run" and "bike" are in the group "cardio," "cardio" would get checked if I check either one)

**Comment by woj-tek** [comment] 2017-10-02 13:36
Definitely +1. I have a set of "morning routine" habits and this would greatly help have it in check.

**Comment by SomMeri** [comment] 2018-01-29 21:09
It would be great if I could merge multiple habits into single history/strength widget.

**Comment by iSoron** [comment] 2019-08-13 22:37
Duplicate of #495. Keeping that one since it has more comments.

**Closed by iSoron** 2019-08-13 22:37 UTC
