### ISSUE TITLE
Can’t customize notifications

### ISSUE THREAD

**Issue by sebalis** [iSoron/uhabits#766] opened 2021-02-06 15:35 UTC
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
When I open the app’s settings and tap on “Customize Notifications”, nothing happens.

## Steps to reproduce
See above. I’d love the change the tone but it doesn’t seem possible.

## System information
 - Phone: Fairphone 2
 - Phone Operating System: Android 7.1.2 (as shipped in the last release of “Fairphone Open”, the FP’2 Google-free Android version)
 - App version: 1.8.12

**Comment by bsaunder2002** [comment] 2021-02-06 21:01
I also have this.  Android 6.0 phone.  Settings / Customize notifications looks like other settings ie not greyed out.  Unfortunately clicking on it does nothing.
I seem to remember this working in older versions.  (ie know it worked).
f-droid built v1.8.10

**Comment by hiqua** [comment] 2021-02-07 17:38
>  I seem to remember this working in older versions. (ie know it worked).

The commit that introduced this change seems to be: aadfac68cd5872209c4313ccca4f7a1f6101c9ea

Before that, these options were available:
![2021-02-07-180021_416x253_scrot](https://user-images.githubusercontent.com/3812042/107153563-7bd7ee80-696e-11eb-9079-5ed4cb512173.png)


Related:
https://github.com/iSoron/uhabits/issues/400

It's still unclear to me whether we want to restore the functionality (not sure how much is still there), or just hide the settings for older devices.

**Comment by iSoron** [comment] 2021-02-09 02:52
Thank you for the bug report, @sebalis and @bsaunder2002. I was able to reproduce the bug here.

**Comment by sebalis** [comment] 2021-02-09 10:01
Looking at the commit that references this report, it seems like you’re going the way @hiqua suggested, which is to make it impossible to make those customizations on older devices such as mine. Obviously I can’t tell you what to do but I would be sad about that, as I can assure you that my Android might be old, but it’s not too old to offer a choice of tones :-)

**Comment by hiqua** [comment] 2021-02-09 10:15
> Looking at the commit that references this report, it seems like you’re going the way @hiqua suggested, which is to make it impossible to make those customizations on older devices such as mine. Obviously I can’t tell you what to do but I would be sad about that, as I can assure you that my Android might be old, but it’s not too old to offer a choice of tones :-)

Nope we're putting the option back so no worries! https://github.com/iSoron/uhabits/pull/776

**Comment by sebalis** [comment] 2021-02-09 10:37
You are very kind :-)

**Comment by iSoron** [comment] 2021-02-09 13:42
This issue has been fixed in #776, but I am planning to backport the fix to 1.8 and release it as part of Loop 1.8.13. I will keep this issue open until then.

**Comment by bsaunder2002** [comment] 2021-03-12 17:42
Hello,
Thanks for working this issue.  I have an old Android 6.0 phone that I don't want to update.  I also don't use the play store and use fdroid instead.  I see fix is merged into 1.8.13 but it appears that's not released yet.  Fdroid only has 1.8.12.
Is there a nightlies were I can download a beta of 1.8.13?  I swore I saw a release build in one of your tickets but now cant find a link.  It was for a 2.x I think.

Ressurected my tcl script and realized I just had my own format sqlite db and the script translated it into uhabits format.  Still, works well.  I edit my simple db in sqlitestudio-2.1.5, translate it to uhabits format db via my tcl script, email it to my phone, flush the data (I know statistics are gone) and import the db into Loop Habits and away I go.

My use case may be unique in that Im trying to organize as much of my 24 hour day as possible.  I have 23 habits to track and editting on the computer saves a ton of time.

I also saw the 1.8.12 has 4 tables but I havent investigated them yet.

The 1.8.13 beta/release is needed so I can customize the notifications and finish adopting this solution for my disorganization. :) 
Bill

**Comment by iSoron** [comment] 2021-03-15 22:02
> Is there a nightlies were I can download a beta of 1.8.13? I swore I saw a release build in one of your tickets but now cant find a link. It was for a 2.x I think.

Loop 1.8.13 does not exist yet. We do have [Loop 2.0.0-alpha](https://github.com/iSoron/uhabits/releases/tag/v2.0.0-alpha).

**Comment by bsaunder2002** [comment] 2021-03-17 18:36
Thanks for the link.  I tried on my Android 6.0 device and it said it failed to install.  Did not investigate.

I'll roll back to something pre 1.8.12 to get the notification customizations and wait for 1.8.13 to be released.

**Comment by iSoron** [comment] 2021-04-18 03:00
Closing as I no longer plan to release any new 1.8.x versions. We will focus on releasing 2.0.x instead.

**Closed by iSoron** 2021-04-18 03:00 UTC
Labels: bug, confirmed

**Comment by sebalis** [comment] 2021-04-18 11:08
I for one would love to have some new version on F-Droid sooner rather than later, as I’ve just now had another one of those moments when I thought for a few seconds that a text message had arrived, only to realise that it was a habit reminder. Do whatever you want with that (non-)information, but I wanted to mention it. :-)
