### ISSUE TITLE
Folder or category to group habits

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#110] opened 2016-05-23 01:07 UTC
(Translating some user feedback from Google Play Store)
...If there were some mechanism to group ~~apps~~ habits, (such as folders or category) it'd be great!

EDIT:
not apps, habits.

**Comment by AnderRasoVazquez** [comment] 2016-05-23 01:13
I like the idea! Imagine the "folder" health with 5 or 6 habits. It's habit strength could be the average habit strength of it's habits and the user would know how is he doing on his health in general.

**Comment by iSoron** [comment] 2016-05-23 10:47
Thank you for translating. I am more inclined to add tags, rather than folders, since you would then be able to assign a habit to multiple categories. I am closing this as a duplicate of #31.

**Closed by iSoron** 2016-05-23 10:47 UTC

**Comment by antre-mate** [comment] 2023-11-19 11:36
Tags and folders are different concept. Colors are already an art of tag. 
1) The biggest advantage of folder is the possibility to **close** it and skip by the habit revision.
- You can have all bad habits for example inside, and you just open the folder in case you did one of these habits.
2) Using folders it would be great to have the possibility to **mark the whole folder** with a ✓ or a ✗.
- that would be specially useful for routines:  A group of habits that you have managed to chain together.


Thank you for your work guys! ♡ 
I really love the app, and it helps me to be a best person

**Comment by ezio-melotti** [comment] 2023-11-20 02:00
See also these feature requests:
* https://github.com/iSoron/uhabits/discussions/495
* https://github.com/iSoron/uhabits/discussions/31 (already linked above, repeated here for convenience)
