### ISSUE TITLE
Habit ticked by default

### ISSUE THREAD

**Issue by patrickferguson95** [iSoron/uhabits#586] opened 2020-06-05 23:25 UTC
Suggestion: give users an option to have a habit ticked by default. This would make it easier to track habits that will be ticked almost everyday. For example, the avoidance of a bad habit ("didn't smoke"); or a habit that has become a genuine daily habit and no longer benefits from ticking off each day.

**Comment by chennemann** [comment] 2020-06-06 08:49
I don't think this is a good idea. If you really believe you managed to implement a new habit into your life you should archive it instead. Checking off a habit automatically bears the inherent risk of forgetting about it completely and it removes the reward of accomplishing something. 

So as I said if you think of the checking of more as a chore than a reward you should just archive said habit and focus on the other ones. Just like you wouldn't check of the habit of going to the toilet.

**Comment by patrickferguson95** [comment] 2020-06-09 11:52
The operative word here is "almost": you can't track an archived habit. 

> [...] you should archive it instead. Checking off a habit automatically bears the inherent risk of forgetting about it completely and it removes the reward of accomplishing something.

Archiving is worse in both respects. 

Moreover, the app isn't for dictating how users should track habits based on questionable folk psychology. Feasibility of implementation or the need for a simple UI are more reasonable objections. 

> didn't smoke

> going to the toilet.

Really, lol?

**Comment by iSoron** [comment] 2020-07-25 14:28
Duplicate of #125

**Closed by iSoron** 2020-07-25 14:28 UTC
