### ISSUE TITLE
ticking off reminder doesn't tick off in app

### ISSUE THREAD

**Issue by hoschi-it** [iSoron/uhabits#228] opened 2016-12-28 08:18 UTC
(Android 5.1, no google play services)
When I tick off that I did stuff at the reminder and then open the app it says stuff still has to be done.

Thanks!

**Comment by iSoron** [comment] 2017-01-13 02:27
Thank you for reporting this but, @hoschi-it. I have not been able to reproduce this bug myself, but a few other users have reported it too, so I am marking this as confirmed. What version of the app are you using?  Also, does this happen consistently, or just sometimes?

**Comment by hoschi-it** [comment] 2017-01-13 06:38
It's version 1.6.2
and as I mentioned: No google play services installed on the phone

**Comment by hoschi-it** [comment] 2017-01-13 06:40
The problem is steady, it's like this every time.

**Comment by fr34q** [comment] 2017-02-15 08:15
Same issue here. However I noticed that it might be updated in the underlying data model but not in the app gui. I tried to manually check it afterwards in the app leading to a short flicker of the checkmark but then it was unchecked again.

**Comment by recheej** [comment] 2017-02-27 01:43
@hoschi-it @fr34q Can either of you guys list the exact steps you took to see the bug? I can't reproduce it right now. Also your device details would be great. Thanks!

**Comment by hoschi-it** [comment] 2017-02-27 14:51
Meanwhile it works for me.
Using Fairphone Open OS 17.01.0 (Android Custom ROM) on Fairphone 2
I guess, the last OS update brought the change.

@recheej Thanks!!

**Comment by recheej** [comment] 2017-02-27 15:12
@hoschi-it Are you saying you're no longer seeing the issue after you updated your OS?

**Comment by fr34q** [comment] 2017-02-28 17:43
@recheej I tried to figure out how I can reproduce the issue, as it seems to work if I check at the notification and directly afterwards check in the app...
I haven't quite figured it out yet but my assumption is that something like the following may work:
1. Create 2 habits and also reminder for them
2. Close the app
3. For a day or two only check both habits via the notification without starting the app
4. A day later, only check one of the habits (again via the notification).
5. Some time later open the app
In my latest test the habit I haven't checked the last day had no ticks also for the days before while the other habit had... Also when now trying to set the ticks for the first habit I had to tap two times in order to set it like I described before.

My phone is a Samsung Galaxy S4 Mini with Android 4.4.2 (no jailbreak or other modifications).

**Comment by iSoron** [comment] 2017-04-02 12:25
For everyone suffering from this issue, could you try to update to the beta version (1.6.2) and then press "Repair database" on the settings screen?

**Comment by devurandom** [comment] 2017-04-02 13:34
I would love to, but the "beta programme is full".

**Comment by iSoron** [comment] 2017-04-02 13:40
@devurandom Thank you for letting me know. I have increased the number of beta testers. You should be able to download it in a few hours.

**Comment by devurandom** [comment] 2017-04-02 17:21
@iSoron Thanks for the hint about the beta! After updating to 1.6.2, even before I ran the database repair (which I did), my habits showed a lot more ticks.

**Comment by fr34q** [comment] 2017-04-02 19:44
@iSoron Thanks for the update. I experienced the same behavior as @devurandom
I will check the next days if missing ticks still occur but so far it looks good.

**Comment by devurandom** [comment] 2017-04-03 06:47
I have to bring bad news: Android takes a screenshot when closing applications, which it stores and shows in the running-application switcher. When one opens an application from there, it will smoothly blend over to the current screen of the application. Now the bad news: While it was blending over, I saw ticks vanish. Which means: The last time the application was running, there were more ticks than when I switched to / started it today. Database repair did not restore those ticks.

**Comment by devurandom** [comment] 2017-04-05 21:06
I just noticed that Android tends to show old screenshots in the running-application switcher. Thus my last comment is very likely moot in that I did not actually observe an issue but expected behaviour of the running-application switcher.

**Comment by ravemir** [comment] 2017-04-19 16:27
I have experienced this issue as well (reported it in a review, recently), but I believed it was related to ticking off as 'Done' on notifications from the lockscreen.

**Comment by fr34q** [comment] 2017-05-01 07:18
@iSoron I could not reproduce the issue anymore since I updated to the beta version a month ago - seems to be fixed now. Thank you!

**Comment by devurandom** [comment] 2017-05-20 16:38
I believe this can be closed? @ravemir ?

**Comment by iSoron** [comment] 2017-05-20 21:35
Yes, I think this has been solved. If anyone still experiences it, let us know, and I will reopen the bug.

**Closed by iSoron** 2017-05-20 21:35 UTC
Labels: confirmed, critical-bug

**Comment by ravemir** [comment] 2017-05-29 16:56
Sorry, @devurandom: last I tested, yes, I believe it is now working.
