### ISSUE TITLE
All notifications dismissed at once

### ISSUE THREAD

**Issue by rdadkins** [iSoron/uhabits#540] opened 2020-01-03 01:13 UTC
Phone: Samsung Galaxy S9 Android 10 Beta 
App Version: 1.8

Scenario: two or more notifications present, click the "Yes" option and notice all notifications are dismissed at once. The habit that I clicked "Yes" on goes through but the rest are not marked.

What should happen: only the notification that I click "Yes" or "No" should disappear.

**Comment by iSoron** [comment] 2020-01-03 02:47
Thank you for the bug report, @rdadkins. Another user reported a similar issue, but was not able to reproduce it. Is this happening consistently for you? Did this happening with version 1.8.2, or an earlier beta version? If this happens again, could you please open the main app and submit a bug report from the settings?

**Comment by spncrhrstn** [comment] 2020-01-03 06:35
@iSoron I've been experiencing this issue too. Only seen the issue since the 1.8.0 (or 1.8.1 or 1.8.2 but at least 1.8.0). It happens consistently when there are multiple habits in the notification shade. Expanding one habit, selecting Yes or No, and then all the notifications disappear. The selected habit is updated, but none of the others.   

Bug report just after it occurs: [https://pastebin.com/raw/QusWEq8p](https://pastebin.com/raw/QusWEq8p)  

Recording: [https://i.imgur.com/aPXWxrL.mp4](https://i.imgur.com/aPXWxrL.mp4)

**Comment by iSoron** [comment] 2020-01-04 22:53
@rdadkins @spncrhrstn Could you please try out the new beta version (1.8.5), released today on Google Play, and let me know if this problem is still happening? Thank you for your help.

**Comment by spncrhrstn** [comment] 2020-01-05 05:07
Just tried it out on 1.8.5, problem is no longer occuring. Thank you for the fix!

**Comment by iSoron** [comment] 2020-01-07 00:12
I just verified that the issue is still there in version 1.8.6. Steps to reproduce:

1. Install the app and create two habits with reminders.
2. Open the About screen and tap the version number 5 times to activate developer mode.
3. Select both habits, tap the overflow icon and select "Reminder". Two notifications should show up.
4. Open the recent apps screen and swipe Loop Habit Tracker away, to force the application close.
5. Tap either "Yes" or "No" on the first notification. The second one will be incorrectly dismissed too.

**Comment by spncrhrstn** [comment] 2020-01-07 01:50
@iSoron there's also another bug I noticed that is probably related to this. If there are multiple notifications, swiping one away will also dismiss all the other ones. This is occurring in 1.8.6 and I believe it's been happening since the 1.8 update. Previous to that update, swiping notifications would only swipe that specific one away.

**Closed** 2020-01-20 13:06 UTC
Labels: bug, confirmed
