### ISSUE TITLE
The statistics needs a minor upgrade

### ISSUE THREAD

**Issue by dummifiedme** [iSoron/uhabits#936] opened 2021-05-29 10:14 UTC
The habit in the screenshot has 16 hours per day target. When we view it at the dashboard, it remains grey untill we hit that goal. 
eg. if target is 16 hours and we input 12 hours, it remains greyed while 16 or more will highlight it with the colour assigned to it (in this case yellow). 

But, when we open the stats for that habit, and look at the bar graph (daily), we can see even the 12 hours and 13 hours values are coloured yellow. It doesn't effectively show the 'failed' days. (Screenshot Attached)

There can be two ways around it:

- Have a horizontal 'target' level dashed line across the chart. Any bar rising above it would be 'achieved' state.
- Have a dull or discoloured graph(bar) for the 'failed' value/day.

![Screenshot_2021-05-29-07-57-43-294_org isoron uhabits](https://user-images.githubusercontent.com/68785729/120066421-e59e1480-c093-11eb-979c-e538fda8ff75.jpg)

I hope I am able to convey my concern/suggestion. (if not, ask away)
I love the app nonetheless, but I see it as my contribution for the betterment.

**Comment by iSoron** [comment] 2021-05-29 12:35
Thank you for the feature request, @dummifiedme. I'm closing as duplicate of #918. Please feel free to repost the text/screenshots in that thread.

**Closed by iSoron** 2021-05-29 12:35 UTC
