### ISSUE TITLE
Real/integer-valued habits

### ISSUE THREAD

**Issue by naught101** [iSoron/uhabits#424] opened 2018-06-26 11:34 UTC
It would be really cool to have the option of setting an integer or real-value target on habits.

e.g. if I want to practice guitar 4 hours a week, then it would be nice if I could put in that I practised 0.5 hours one day, 1.0 hours another day, and so on. Or if I wanted to try to reach 5o push-ups a day, then I could say I did 10 the first day, 12 the next, etc.

The UI could be almost the same, except when clicking the tick mark, a value pop-up would appear, allowing me to enter the values for the day.

**Comment by Yumi08** [comment] 2018-07-09 22:37
I really like that idea!

I can also think of some different input types that could be used. Such as a time measurement, like you said, or scientific measurements like distance or volume, and other things like repititions, currency values, and maybe even user-definable units!

**Comment by iSoron** [comment] 2018-08-12 02:57
This is a duplicate of #42.

**Closed by iSoron** 2018-08-12 02:57 UTC
