### ISSUE TITLE
Several reminders per day

### ISSUE THREAD

**Issue by MazeWebArchitect** [iSoron/uhabits#313] opened 2017-07-12 17:59 UTC
It would be nice to be able to set several reminders for a habit, which shall be completed several times during the day. Applicable examples:
- sports in the morning and evening
- medication throughout the day
- drinking/eating habits
For these type of habits it is not sufficient to just snooze the alarm - especially since the snooze time is now fixed for all habits and not individually adjustable.The only
The only option atm is to create a habit for each time (e.g. three medication habits) which is kind of a downside, since it clutters the overview.

**Comment by imme-emosol** [comment] 2017-07-18 05:54
Perhaps there could be some integration with for instance https://gitlab.com/CiaranG/tallyphant or https://github.com/gentlecat/counter/blob/HEAD/README.md for counting multiple occurences of a certain habit .

**Comment by iSoron** [comment] 2017-07-18 19:00
Duplicate of #179

**Closed by iSoron** 2017-07-18 19:00 UTC

**Comment by imme-emosol** [comment] 2017-07-18 20:50
Or duplicate of #121 .. (for people getting here).
#179 seems to be for multiple reminders .
#121 seems to be for multiple logged entries per day .
