### ISSUE TITLE
Add scale of 1 to 10 for answering a question

### ISSUE THREAD

**Issue by shyamamrawat** [iSoron/uhabits#249] opened 2017-01-26 17:46 UTC
Currently application provide two options for any "Did I do my best.." questions: Yes or No. Whereas Ideally efforts cannot be measured in binary. So we should provide option to scale the efforts between zero to ten.

This is recommended by Marshall Goldsmith in his book TRIGGERS. It has superior benefits over Yes & No.

Personally I want to contribute to develop this feature.

Thanks

**Comment by iSoron** [comment] 2017-02-03 02:48
Thank you for the suggestion. This is a duplicate of #42.

**Closed by iSoron** 2017-02-03 02:48 UTC

**Comment by shyamamrawat** [comment] 2017-02-03 02:58
Hello,

Thanks for acknowledging my request.
It looks that #42 MAY also address my request. But i see one difference in
philosophy of "did i do my best" question.

#42 say, people wants to track numbers of weights, books etc. These are
explicit in nature where as my request is to gadge/measure determent
efforts put on to achieve the goal. Bcs it gives real feedback to the
person of how much is he determined to achieve the goal.

Regards
Shtam

**Comment by iSoron** [comment] 2017-02-03 03:09
Although #42 is more focused on tracking the number of things you did, your situation is also an important case that I had in mind. It will certainly be possible to use numerical habits to track "how well did you did something" in a scale from zero to ten. It will depend on how do you want to use the feature.

**Comment by shyamamrawat** [comment] 2017-02-03 03:14
Thank you.
Will wait for the feature.
Regards
