### ISSUE TITLE
Allow to sort habits in reverse order

### ISSUE THREAD

**Issue by shervinemami** [iSoron/uhabits#678] opened 2020-12-13 09:49 UTC
Hi, it would be great if there was a way to sort in reverse order, such as if you tapped the same Sort method that was already selected. A good use case is to sort by reverse scores, so if you've listed all the habits that you want to achieve, the most important ones (ie: the ones with lowest score) are right at the top.

**Comment by iSoron** [comment] 2020-12-13 12:36
Duplicate of #497

**Closed by iSoron** 2020-12-13 12:36 UTC
