### ISSUE TITLE
The video of task disapearing

### ISSUE THREAD

**Issue by TGSunrise** [iSoron/uhabits#1633] opened 2023-01-26 08:11 UTC
## Pre-submission checklist
- [✓ ] I am submitting a bug report, not a feature request.
- [✓]] I have searched for similar issues, but did not find any matches.

## Description
A clear and concise description of what the problem is.
This is the video of task disapearing refering to my older post
## Steps to reproduce
1. Go to ...
2. Click on ....
3. Scroll down to ....

## System information
 - Phone: [Motorola 20 edge]
 - Phone Operating System: [ Android 11]
 - App version: [e.g. 2.0.2]

## Screenshots

https://user-images.githubusercontent.com/123624564/214786530-e3f27e9e-5f32-44a6-9860-359d18bdac58.mp4

#1632 The post name was i was clicking on a task and the section disapeared

**Comment by iSoron** [comment] 2023-01-26 09:16
Duplicate of #1632

**Closed by iSoron** 2023-01-26 09:16 UTC
