### ISSUE TITLE
Streak calculation for non-daily habits is inconsistent

### ISSUE THREAD

**Issue by Alp7** [iSoron/uhabits#554] opened 2020-02-03 14:57 UTC
Take a look at this example:

![SS2](https://user-images.githubusercontent.com/60614101/73662570-f606d080-4693-11ea-9e45-665bb3429f0d.png)

I set a habit to track my workouts, which I do three times a week. As you can see in the pic, it did not count second and fourth day of the first week even though I did that habit three times that week. And as you can see with last week, even though I did it 3 times, it did not mark all the days of that week. This creates a mess in streaks history.

Also, I don't think it should count "rest days" for the streak, or at least we should have an option. In other habit apps, such as Habithub, we have options like:

Fixed - If you gonna do that habit only on specific days, so I can set it to Monday, Thursday, Friday which is essentially 3 times a week but it is not flexible. Simply set every day of the week for daily habits.

Flexible - I can set 3 times a week, and it counts as long as I do that habit any 3 days of that week, which is what I need for my workout routine.

Repeating - Every x days. Self explanatory.

Also, it counts streaks differently than Loop. For example, in the pic above, I did my workout for 12 days in last 4 weeks, so my current streak is 12. Streak ends once I won't do 3 times in a week. Which is I think more efficient and makes more sense.

Even with current Loop method, my streak should start from Jan 6 to Feb 1.

**Comment by iSoron** [comment] 2020-03-01 20:20
This is a duplicate of #124. Please try out the beta version of the app; this has been fixed.

**Closed by iSoron** 2020-03-01 20:20 UTC
