### ISSUE TITLE
Widget size change disfunction

### ISSUE THREAD

**Issue by IsaacFurlani** [iSoron/uhabits#930] opened 2021-05-24 20:06 UTC
This is an old bug that had been fixed, it seems to have arisen again.

The Android version previously allowed most widgets to be sized from 1x1 up to 5x6.
This then allowed the 'Habit Strength' linear chart to be stretched horizontally with minimal height (5x1). Resulting in a nice looking chart across the screen, that could then be stacked on top of 5 other charts of different habits.
However, the recent update now allows a minimum height of 2 rows. Thus, cutting in half the number of charts available to display on the home screen, from 6 to just 3.

Could the developers please look at changing it back to a minimum widget height of 1 column?
I should also add, thank you for fixing it so quickly last time this happened.

System information
 - Phone: Samsung Note10 plus
 - Operating System: Android 11
 - App version: 1.8.12

**Comment by iSoron** [comment] 2021-05-25 00:40
Thank you for the bug report, @IsaacFurlani, but is the intended behavior. All of our graph widgets have a minimum grid size of 2x2. We have also not made any changes to the minimum size of widgets in the last few years; it looks like Samsung was (incorrectly) ignoring this restriction before, and have recently (correctly) started enforcing it.

I'm closing as this is not a bug, but feel free to open a feature request for 1x1 graph widgets.

**Closed by iSoron** 2021-05-25 00:40 UTC
