### ISSUE TITLE
Idea: Third Status "Unknown"

### ISSUE THREAD

**Issue by r4taw2mg** [iSoron/uhabits#530] opened 2019-12-14 18:33 UTC
I propose something of a third state for marking your daily progress. Currently there is set and unset. For a habit like: "Do not eat sweets!" I have to sit back at the end of the day and think, if I have violated my rule today. If I am sure, I haven't, I put a check mark.

A third state like "unknown" would solve this problem. As soon as I eat some sweets, I would set the days habit state to "unset". No need to rethink the day after it is done.

For the calculation of habit strength and streakes, I see two ways of handling "unknown": rigid, where every "unknown" counts as "unset", as a violation or lenient, where every "unknown" counts as a "set" value, thus not breaking streaks.

What do you think?

**Comment by And96** [comment] 2019-12-29 11:00
+1

**Comment by iSoron** [comment] 2019-12-29 11:07
Thank you for the suggestion, @r4taw2mg. This is a duplicate of #96.

**Closed by iSoron** 2019-12-29 11:07 UTC
