### ISSUE TITLE
Auto sort habits by habit strength

### ISSUE THREAD

**Issue by xvdd** [iSoron/uhabits#198] opened 2016-10-31 16:06 UTC
It would be nice to have an auto sort of the list of habits by habit strength (either stronger to weaker or weaker to stronger or both with an option).

For some reason (probably because I feel it is part of the "game" to know which habit is stronger than the other) I keep updating the order manually and it is a little tedious as for that, I need to open it and check the strength value and compare to the others..

**Comment by iSoron** [comment] 2016-11-01 14:00
This is a duplicate of #73.

**Closed by iSoron** 2016-11-01 14:00 UTC
